import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

interface StockSeed {
  symbol: string;
  name: string;
  sector: string;
  cap: "Large Cap" | "Mid Cap" | "Small Cap";
}

// Complete NSE + BSE stock list (~2000+ stocks)
const ALL_STOCKS: StockSeed[] = [
  // ============= LARGE CAP STOCKS (Nifty 50 + Nifty Next 50) =============
  { symbol: "RELIANCE", name: "Reliance Industries Ltd", sector: "Oil & Gas", cap: "Large Cap" },
  { symbol: "TCS", name: "Tata Consultancy Services Ltd", sector: "IT", cap: "Large Cap" },
  { symbol: "HDFCBANK", name: "HDFC Bank Ltd", sector: "Banking", cap: "Large Cap" },
  { symbol: "INFY", name: "Infosys Ltd", sector: "IT", cap: "Large Cap" },
  { symbol: "ICICIBANK", name: "ICICI Bank Ltd", sector: "Banking", cap: "Large Cap" },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever Ltd", sector: "FMCG", cap: "Large Cap" },
  { symbol: "ITC", name: "ITC Ltd", sector: "FMCG", cap: "Large Cap" },
  { symbol: "SBIN", name: "State Bank of India", sector: "Banking", cap: "Large Cap" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel Ltd", sector: "Telecom", cap: "Large Cap" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank Ltd", sector: "Banking", cap: "Large Cap" },
  { symbol: "BAJFINANCE", name: "Bajaj Finance Ltd", sector: "Finance", cap: "Large Cap" },
  { symbol: "LICI", name: "Life Insurance Corporation", sector: "Insurance", cap: "Large Cap" },
  { symbol: "LT", name: "Larsen & Toubro Ltd", sector: "Infrastructure", cap: "Large Cap" },
  { symbol: "HCLTECH", name: "HCL Technologies Ltd", sector: "IT", cap: "Large Cap" },
  { symbol: "ASIANPAINT", name: "Asian Paints Ltd", sector: "Paints", cap: "Large Cap" },
  { symbol: "AXISBANK", name: "Axis Bank Ltd", sector: "Banking", cap: "Large Cap" },
  { symbol: "MARUTI", name: "Maruti Suzuki India Ltd", sector: "Auto", cap: "Large Cap" },
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical Industries", sector: "Pharma", cap: "Large Cap" },
  { symbol: "TITAN", name: "Titan Company Ltd", sector: "Consumer Goods", cap: "Large Cap" },
  { symbol: "DMART", name: "Avenue Supermarts Ltd", sector: "Retail", cap: "Large Cap" },
  { symbol: "TATAMOTORS", name: "Tata Motors Ltd", sector: "Auto", cap: "Large Cap" },
  { symbol: "NTPC", name: "NTPC Ltd", sector: "Power", cap: "Large Cap" },
  { symbol: "POWERGRID", name: "Power Grid Corporation", sector: "Power", cap: "Large Cap" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement Ltd", sector: "Cement", cap: "Large Cap" },
  { symbol: "WIPRO", name: "Wipro Ltd", sector: "IT", cap: "Large Cap" },
  { symbol: "ONGC", name: "Oil & Natural Gas Corporation", sector: "Oil & Gas", cap: "Large Cap" },
  { symbol: "JSWSTEEL", name: "JSW Steel Ltd", sector: "Metals", cap: "Large Cap" },
  { symbol: "TATASTEEL", name: "Tata Steel Ltd", sector: "Metals", cap: "Large Cap" },
  { symbol: "M&M", name: "Mahindra & Mahindra Ltd", sector: "Auto", cap: "Large Cap" },
  { symbol: "ADANIENT", name: "Adani Enterprises Ltd", sector: "Infrastructure", cap: "Large Cap" },
  { symbol: "ADANIPORTS", name: "Adani Ports & SEZ Ltd", sector: "Infrastructure", cap: "Large Cap" },
  { symbol: "COALINDIA", name: "Coal India Ltd", sector: "Mining", cap: "Large Cap" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv Ltd", sector: "Finance", cap: "Large Cap" },
  { symbol: "TECHM", name: "Tech Mahindra Ltd", sector: "IT", cap: "Large Cap" },
  { symbol: "NESTLEIND", name: "Nestle India Ltd", sector: "FMCG", cap: "Large Cap" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank Ltd", sector: "Banking", cap: "Large Cap" },
  { symbol: "BPCL", name: "Bharat Petroleum Corporation", sector: "Oil & Gas", cap: "Large Cap" },
  { symbol: "HINDALCO", name: "Hindalco Industries Ltd", sector: "Metals", cap: "Large Cap" },
  { symbol: "DIVISLAB", name: "Divi's Laboratories Ltd", sector: "Pharma", cap: "Large Cap" },
  { symbol: "GRASIM", name: "Grasim Industries Ltd", sector: "Cement", cap: "Large Cap" },
  { symbol: "DRREDDY", name: "Dr Reddy's Laboratories", sector: "Pharma", cap: "Large Cap" },
  { symbol: "CIPLA", name: "Cipla Ltd", sector: "Pharma", cap: "Large Cap" },
  { symbol: "EICHERMOT", name: "Eicher Motors Ltd", sector: "Auto", cap: "Large Cap" },
  { symbol: "BRITANNIA", name: "Britannia Industries Ltd", sector: "FMCG", cap: "Large Cap" },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals Enterprise", sector: "Healthcare", cap: "Large Cap" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp Ltd", sector: "Auto", cap: "Large Cap" },
  { symbol: "TATACONSUM", name: "Tata Consumer Products Ltd", sector: "FMCG", cap: "Large Cap" },
  { symbol: "SBILIFE", name: "SBI Life Insurance Company", sector: "Insurance", cap: "Large Cap" },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto Ltd", sector: "Auto", cap: "Large Cap" },
  { symbol: "HDFCLIFE", name: "HDFC Life Insurance Company", sector: "Insurance", cap: "Large Cap" },
  { symbol: "ADANIGREEN", name: "Adani Green Energy Ltd", sector: "Power", cap: "Large Cap" },
  { symbol: "VEDL", name: "Vedanta Ltd", sector: "Mining", cap: "Large Cap" },
  { symbol: "DLF", name: "DLF Ltd", sector: "Real Estate", cap: "Large Cap" },
  { symbol: "GODREJCP", name: "Godrej Consumer Products", sector: "FMCG", cap: "Large Cap" },
  { symbol: "HAVELLS", name: "Havells India Ltd", sector: "Consumer Durables", cap: "Large Cap" },
  { symbol: "SIEMENS", name: "Siemens Ltd", sector: "Engineering", cap: "Large Cap" },
  { symbol: "AMBUJACEM", name: "Ambuja Cements Ltd", sector: "Cement", cap: "Large Cap" },
  { symbol: "DABUR", name: "Dabur India Ltd", sector: "FMCG", cap: "Large Cap" },
  { symbol: "IOC", name: "Indian Oil Corporation Ltd", sector: "Oil & Gas", cap: "Large Cap" },
  { symbol: "BANKBARODA", name: "Bank of Baroda", sector: "Banking", cap: "Large Cap" },
  { symbol: "PNB", name: "Punjab National Bank", sector: "Banking", cap: "Large Cap" },
  { symbol: "PIDILITIND", name: "Pidilite Industries Ltd", sector: "Chemicals", cap: "Large Cap" },
  { symbol: "ICICIPRULI", name: "ICICI Prudential Life Insurance", sector: "Insurance", cap: "Large Cap" },
  { symbol: "ICICIGI", name: "ICICI Lombard General Insurance", sector: "Insurance", cap: "Large Cap" },
  { symbol: "INDIGO", name: "InterGlobe Aviation Ltd", sector: "Aviation", cap: "Large Cap" },
  { symbol: "SHREECEM", name: "Shree Cement Ltd", sector: "Cement", cap: "Large Cap" },
  { symbol: "MARICO", name: "Marico Ltd", sector: "FMCG", cap: "Large Cap" },
  { symbol: "BERGEPAINT", name: "Berger Paints India Ltd", sector: "Paints", cap: "Large Cap" },
  { symbol: "CHOLAFIN", name: "Cholamandalam Investment & Finance", sector: "Finance", cap: "Large Cap" },
  { symbol: "BIOCON", name: "Biocon Ltd", sector: "Pharma", cap: "Large Cap" },
  { symbol: "BOSCHLTD", name: "Bosch Ltd", sector: "Auto Ancillary", cap: "Large Cap" },
  { symbol: "NAUKRI", name: "Info Edge India Ltd", sector: "IT", cap: "Large Cap" },
  { symbol: "COLPAL", name: "Colgate-Palmolive India Ltd", sector: "FMCG", cap: "Large Cap" },
  { symbol: "TORNTPHARM", name: "Torrent Pharmaceuticals Ltd", sector: "Pharma", cap: "Large Cap" },
  { symbol: "MCDOWELL-N", name: "United Spirits Ltd", sector: "FMCG", cap: "Large Cap" },
  { symbol: "GAIL", name: "GAIL India Ltd", sector: "Oil & Gas", cap: "Large Cap" },
  { symbol: "HINDPETRO", name: "Hindustan Petroleum Corporation", sector: "Oil & Gas", cap: "Large Cap" },
  { symbol: "TATAPOWER", name: "Tata Power Company Ltd", sector: "Power", cap: "Large Cap" },
  { symbol: "JINDALSTEL", name: "Jindal Steel & Power Ltd", sector: "Metals", cap: "Large Cap" },
  { symbol: "ZOMATO", name: "Zomato Ltd", sector: "Internet", cap: "Large Cap" },
  { symbol: "HAL", name: "Hindustan Aeronautics Ltd", sector: "Defence", cap: "Large Cap" },
  { symbol: "HINDZINC", name: "Hindustan Zinc Ltd", sector: "Metals", cap: "Large Cap" },
  { symbol: "LTIM", name: "LTIMindtree Ltd", sector: "IT", cap: "Large Cap" },
  { symbol: "LUPIN", name: "Lupin Ltd", sector: "Pharma", cap: "Large Cap" },
  { symbol: "MANKIND", name: "Mankind Pharma Ltd", sector: "Pharma", cap: "Large Cap" },
  { symbol: "HDFCAMC", name: "HDFC Asset Management Co", sector: "Finance", cap: "Large Cap" },
  
  // ============= MID CAP STOCKS (Nifty Midcap 150) =============
  { symbol: "MUTHOOTFIN", name: "Muthoot Finance Ltd", sector: "Finance", cap: "Mid Cap" },
  { symbol: "VOLTAS", name: "Voltas Ltd", sector: "Consumer Durables", cap: "Mid Cap" },
  { symbol: "AUROPHARMA", name: "Aurobindo Pharma Ltd", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "TATAELXSI", name: "Tata Elxsi Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "PERSISTENT", name: "Persistent Systems Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "COFORGE", name: "Coforge Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "POLYCAB", name: "Polycab India Ltd", sector: "Cables", cap: "Mid Cap" },
  { symbol: "TRENT", name: "Trent Ltd", sector: "Retail", cap: "Mid Cap" },
  { symbol: "MPHASIS", name: "MphasiS Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "FEDERALBNK", name: "Federal Bank Ltd", sector: "Banking", cap: "Mid Cap" },
  { symbol: "INDHOTEL", name: "Indian Hotels Co Ltd", sector: "Hotels", cap: "Mid Cap" },
  { symbol: "PAGEIND", name: "Page Industries Ltd", sector: "Textiles", cap: "Mid Cap" },
  { symbol: "ASTRAL", name: "Astral Ltd", sector: "Plastics", cap: "Mid Cap" },
  { symbol: "CUMMINSIND", name: "Cummins India Ltd", sector: "Engineering", cap: "Mid Cap" },
  { symbol: "ESCORTS", name: "Escorts Kubota Ltd", sector: "Auto", cap: "Mid Cap" },
  { symbol: "OBEROIRLTY", name: "Oberoi Realty Ltd", sector: "Real Estate", cap: "Mid Cap" },
  { symbol: "LTTS", name: "L&T Technology Services", sector: "IT", cap: "Mid Cap" },
  { symbol: "LALPATHLAB", name: "Dr Lal PathLabs Ltd", sector: "Healthcare", cap: "Mid Cap" },
  { symbol: "ASHOKLEY", name: "Ashok Leyland Ltd", sector: "Auto", cap: "Mid Cap" },
  { symbol: "CROMPTON", name: "Crompton Greaves Consumer", sector: "Consumer Durables", cap: "Mid Cap" },
  { symbol: "ACC", name: "ACC Ltd", sector: "Cement", cap: "Mid Cap" },
  { symbol: "ATUL", name: "Atul Ltd", sector: "Chemicals", cap: "Mid Cap" },
  { symbol: "SYNGENE", name: "Syngene International Ltd", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "COROMANDEL", name: "Coromandel International Ltd", sector: "Fertilizers", cap: "Mid Cap" },
  { symbol: "CONCOR", name: "Container Corporation of India", sector: "Logistics", cap: "Mid Cap" },
  { symbol: "DIXON", name: "Dixon Technologies India Ltd", sector: "Consumer Electronics", cap: "Mid Cap" },
  { symbol: "AUBANK", name: "AU Small Finance Bank Ltd", sector: "Banking", cap: "Mid Cap" },
  { symbol: "NMDC", name: "NMDC Ltd", sector: "Mining", cap: "Mid Cap" },
  { symbol: "ALKEM", name: "Alkem Laboratories Ltd", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "IDFCFIRSTB", name: "IDFC First Bank Ltd", sector: "Banking", cap: "Mid Cap" },
  { symbol: "BALKRISIND", name: "Balkrishna Industries Ltd", sector: "Auto Ancillary", cap: "Mid Cap" },
  { symbol: "TATACOMM", name: "Tata Communications Ltd", sector: "Telecom", cap: "Mid Cap" },
  { symbol: "SAIL", name: "Steel Authority of India Ltd", sector: "Metals", cap: "Mid Cap" },
  { symbol: "PETRONET", name: "Petronet LNG Ltd", sector: "Oil & Gas", cap: "Mid Cap" },
  { symbol: "BHARATFORG", name: "Bharat Forge Ltd", sector: "Auto Ancillary", cap: "Mid Cap" },
  { symbol: "SRIRAMFIN", name: "Shriram Finance Ltd", sector: "Finance", cap: "Mid Cap" },
  { symbol: "UNIONBANK", name: "Union Bank of India", sector: "Banking", cap: "Mid Cap" },
  { symbol: "BANDHANBNK", name: "Bandhan Bank Ltd", sector: "Banking", cap: "Mid Cap" },
  { symbol: "CANBK", name: "Canara Bank", sector: "Banking", cap: "Mid Cap" },
  { symbol: "INDUSTOWER", name: "Indus Towers Ltd", sector: "Telecom", cap: "Mid Cap" },
  { symbol: "MOTHERSON", name: "Samvardhana Motherson International", sector: "Auto Ancillary", cap: "Mid Cap" },
  { symbol: "JUBLFOOD", name: "Jubilant Foodworks Ltd", sector: "QSR", cap: "Mid Cap" },
  { symbol: "PGHH", name: "Procter & Gamble Hygiene", sector: "FMCG", cap: "Mid Cap" },
  { symbol: "MAXHEALTH", name: "Max Healthcare Institute", sector: "Healthcare", cap: "Mid Cap" },
  { symbol: "RECLTD", name: "REC Ltd", sector: "Finance", cap: "Mid Cap" },
  { symbol: "PFC", name: "Power Finance Corporation Ltd", sector: "Finance", cap: "Mid Cap" },
  { symbol: "SUNDARMFIN", name: "Sundaram Finance Ltd", sector: "Finance", cap: "Mid Cap" },
  { symbol: "PRESTIGE", name: "Prestige Estates Projects", sector: "Real Estate", cap: "Mid Cap" },
  { symbol: "PHOENIXLTD", name: "Phoenix Mills Ltd", sector: "Real Estate", cap: "Mid Cap" },
  { symbol: "ZYDUSLIFE", name: "Zydus Lifesciences Ltd", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "METROPOLIS", name: "Metropolis Healthcare Ltd", sector: "Healthcare", cap: "Mid Cap" },
  { symbol: "AFFLE", name: "Affle India Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "LAURUSLABS", name: "Laurus Labs Ltd", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "DEEPAKNTR", name: "Deepak Nitrite Ltd", sector: "Chemicals", cap: "Mid Cap" },
  { symbol: "IIFL", name: "IIFL Finance Ltd", sector: "Finance", cap: "Mid Cap" },
  { symbol: "HONAUT", name: "Honeywell Automation India", sector: "Engineering", cap: "Mid Cap" },
  { symbol: "MRF", name: "MRF Ltd", sector: "Auto Ancillary", cap: "Mid Cap" },
  { symbol: "GUJGASLTD", name: "Gujarat Gas Ltd", sector: "Oil & Gas", cap: "Mid Cap" },
  { symbol: "THERMAX", name: "Thermax Ltd", sector: "Engineering", cap: "Mid Cap" },
  { symbol: "SUPREMEIND", name: "Supreme Industries Ltd", sector: "Plastics", cap: "Mid Cap" },
  { symbol: "BATAINDIA", name: "Bata India Ltd", sector: "Footwear", cap: "Mid Cap" },
  { symbol: "WHIRLPOOL", name: "Whirlpool of India Ltd", sector: "Consumer Durables", cap: "Mid Cap" },
  { symbol: "KANSAINER", name: "Kansai Nerolac Paints Ltd", sector: "Paints", cap: "Mid Cap" },
  { symbol: "ABFRL", name: "Aditya Birla Fashion & Retail", sector: "Retail", cap: "Mid Cap" },
  { symbol: "APOLLOTYRE", name: "Apollo Tyres Ltd", sector: "Auto Ancillary", cap: "Mid Cap" },
  { symbol: "IPCALAB", name: "IPCA Laboratories Ltd", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "NATCOPHARM", name: "Natco Pharma Ltd", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "BLUEDART", name: "Blue Dart Express Ltd", sector: "Logistics", cap: "Mid Cap" },
  { symbol: "RELAXO", name: "Relaxo Footwears Ltd", sector: "Footwear", cap: "Mid Cap" },
  { symbol: "JUBILANT", name: "Jubilant Pharmova Ltd", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "LICHSGFIN", name: "LIC Housing Finance Ltd", sector: "Finance", cap: "Mid Cap" },
  { symbol: "INDIAMART", name: "IndiaMART InterMESH Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "KPITTECH", name: "KPIT Technologies Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "CYIENT", name: "Cyient Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "HAPPSTMNDS", name: "Happiest Minds Technologies", sector: "IT", cap: "Mid Cap" },
  { symbol: "SONACOMS", name: "Sona BLW Precision Forgings", sector: "Auto Ancillary", cap: "Mid Cap" },
  { symbol: "VBL", name: "Varun Beverages Ltd", sector: "FMCG", cap: "Mid Cap" },
  { symbol: "TVSMOTOR", name: "TVS Motor Company Ltd", sector: "Auto", cap: "Mid Cap" },
  { symbol: "BHEL", name: "Bharat Heavy Electricals Ltd", sector: "Engineering", cap: "Mid Cap" },
  { symbol: "IRCTC", name: "Indian Railway Catering", sector: "Travel", cap: "Mid Cap" },
  { symbol: "EXIDEIND", name: "Exide Industries Ltd", sector: "Auto Ancillary", cap: "Mid Cap" },
  { symbol: "GODREJPROP", name: "Godrej Properties Ltd", sector: "Real Estate", cap: "Mid Cap" },
  { symbol: "EMAMILTD", name: "Emami Ltd", sector: "FMCG", cap: "Mid Cap" },
  { symbol: "SUNDRMFAST", name: "Sundram Fasteners Ltd", sector: "Auto Ancillary", cap: "Mid Cap" },
  { symbol: "RADICO", name: "Radico Khaitan Ltd", sector: "FMCG", cap: "Mid Cap" },
  { symbol: "FORTIS", name: "Fortis Healthcare Ltd", sector: "Healthcare", cap: "Mid Cap" },
  { symbol: "SONATSOFTW", name: "Sonata Software Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "MANAPPURAM", name: "Manappuram Finance Ltd", sector: "Finance", cap: "Mid Cap" },
  { symbol: "GMRINFRA", name: "GMR Infrastructure Ltd", sector: "Infrastructure", cap: "Mid Cap" },
  { symbol: "SKFINDIA", name: "SKF India Ltd", sector: "Engineering", cap: "Mid Cap" },
  { symbol: "BLUESTARCO", name: "Blue Star Ltd", sector: "Consumer Durables", cap: "Mid Cap" },
  { symbol: "TIMKEN", name: "Timken India Ltd", sector: "Engineering", cap: "Mid Cap" },
  { symbol: "CASTROLIND", name: "Castrol India Ltd", sector: "Oil & Gas", cap: "Mid Cap" },
  { symbol: "KAJARIACER", name: "Kajaria Ceramics Ltd", sector: "Building Materials", cap: "Mid Cap" },
  { symbol: "GRINDWELL", name: "Grindwell Norton Ltd", sector: "Engineering", cap: "Mid Cap" },
  { symbol: "MAZDOCK", name: "Mazagon Dock Shipbuilders", sector: "Shipbuilding", cap: "Mid Cap" },
  { symbol: "COCHINSHIP", name: "Cochin Shipyard Ltd", sector: "Shipbuilding", cap: "Mid Cap" },
  { symbol: "BDL", name: "Bharat Dynamics Ltd", sector: "Defence", cap: "Mid Cap" },
  { symbol: "BEML", name: "BEML Ltd", sector: "Engineering", cap: "Mid Cap" },
  { symbol: "HUDCO", name: "Housing & Urban Dev Corp", sector: "Finance", cap: "Mid Cap" },
  { symbol: "IREDA", name: "Indian Renewable Energy Dev Agency", sector: "Finance", cap: "Mid Cap" },
  { symbol: "IRB", name: "IRB Infrastructure Developers", sector: "Infrastructure", cap: "Mid Cap" },
  { symbol: "IRCON", name: "Ircon International Ltd", sector: "Infrastructure", cap: "Mid Cap" },
  { symbol: "GRSE", name: "Garden Reach Shipbuilders", sector: "Shipbuilding", cap: "Mid Cap" },
  { symbol: "HINDCOPPER", name: "Hindustan Copper Ltd", sector: "Metals", cap: "Mid Cap" },
  { symbol: "ENGINERSIN", name: "Engineers India Ltd", sector: "Engineering", cap: "Mid Cap" },
  { symbol: "GNFC", name: "Gujarat Narmada Valley Fertilizers", sector: "Fertilizers", cap: "Mid Cap" },
  { symbol: "GSFC", name: "Gujarat State Fertilizers", sector: "Fertilizers", cap: "Mid Cap" },
  { symbol: "GUJALKALI", name: "Gujarat Alkalies And Chemicals", sector: "Chemicals", cap: "Mid Cap" },
  { symbol: "FLUOROCHEM", name: "Gujarat Fluorochemicals Ltd", sector: "Chemicals", cap: "Mid Cap" },
  { symbol: "CLEAN", name: "Clean Science & Technology", sector: "Chemicals", cap: "Mid Cap" },
  { symbol: "FINEORG", name: "Fine Organic Industries", sector: "Chemicals", cap: "Mid Cap" },
  { symbol: "GMMPFAUDLR", name: "GMM Pfaudler Ltd", sector: "Engineering", cap: "Mid Cap" },
  { symbol: "ELGIEQUIP", name: "Elgi Equipments Ltd", sector: "Engineering", cap: "Mid Cap" },
  { symbol: "LAXMIMACH", name: "Lakshmi Machine Works", sector: "Engineering", cap: "Mid Cap" },
  { symbol: "CRAFTSMAN", name: "Craftsman Automation Ltd", sector: "Auto Ancillary", cap: "Mid Cap" },
  { symbol: "CAMPUS", name: "Campus Activewear Ltd", sector: "Footwear", cap: "Mid Cap" },
  { symbol: "METROBRAND", name: "Metro Brands Ltd", sector: "Footwear", cap: "Mid Cap" },
  { symbol: "KALYANKJIL", name: "Kalyan Jewellers India", sector: "Gems & Jewellery", cap: "Mid Cap" },
  { symbol: "DEVYANI", name: "Devyani International Ltd", sector: "QSR", cap: "Mid Cap" },
  { symbol: "LODHA", name: "Macrotech Developers Ltd", sector: "Real Estate", cap: "Mid Cap" },
  { symbol: "BRIGADE", name: "Brigade Enterprises Ltd", sector: "Real Estate", cap: "Mid Cap" },
  { symbol: "MAHLIFE", name: "Mahindra Lifespace Developers", sector: "Real Estate", cap: "Mid Cap" },
  { symbol: "GLAND", name: "Gland Pharma Ltd", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "GLAXO", name: "GlaxoSmithKline Pharmaceuticals", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "GLENMARK", name: "Glenmark Pharmaceuticals", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "CAPLIPOINT", name: "Caplin Point Laboratories", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "JBCHEPHARM", name: "JB Chemicals & Pharmaceuticals", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "GLOBALHEALT", name: "Global Health Ltd", sector: "Healthcare", cap: "Mid Cap" },
  { symbol: "MEDPLUS", name: "MedPlus Health Services", sector: "Healthcare", cap: "Mid Cap" },
  { symbol: "EIHOTEL", name: "EIH Ltd", sector: "Hotels", cap: "Mid Cap" },
  { symbol: "MHRIL", name: "Mahindra Holidays & Resorts", sector: "Hotels", cap: "Mid Cap" },
  { symbol: "CHALET", name: "Chalet Hotels Ltd", sector: "Hotels", cap: "Mid Cap" },
  { symbol: "LATENTVIEW", name: "Latent View Analytics Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "MAPMYINDIA", name: "CE Info Systems Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "INTELLECT", name: "Intellect Design Arena", sector: "IT", cap: "Mid Cap" },
  { symbol: "MASTEK", name: "Mastek Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "JUSTDIAL", name: "Just Dial Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "CDSL", name: "Central Depository Services", sector: "Finance", cap: "Mid Cap" },
  { symbol: "MCX", name: "Multi Commodity Exchange", sector: "Finance", cap: "Mid Cap" },
  { symbol: "MOTILALOFS", name: "Motilal Oswal Financial Services", sector: "Finance", cap: "Mid Cap" },
  { symbol: "ANGELONE", name: "Angel One Ltd", sector: "Finance", cap: "Mid Cap" },
  { symbol: "ISEC", name: "ICICI Securities Ltd", sector: "Finance", cap: "Mid Cap" },
  { symbol: "CRISIL", name: "CRISIL Ltd", sector: "Finance", cap: "Mid Cap" },
  { symbol: "APTUS", name: "Aptus Value Housing Finance", sector: "Finance", cap: "Mid Cap" },
  { symbol: "HOMEFIRST", name: "Home First Finance Company", sector: "Finance", cap: "Mid Cap" },
  { symbol: "FIVESTAR", name: "Five-Star Business Finance", sector: "Finance", cap: "Mid Cap" },
  { symbol: "CHAMBLFERT", name: "Chambal Fertilisers & Chemicals", sector: "Fertilizers", cap: "Mid Cap" },
  { symbol: "DCMSHRIRAM", name: "DCM Shriram Ltd", sector: "Diversified", cap: "Mid Cap" },
  { symbol: "APARINDS", name: "Apar Industries Ltd", sector: "Cables", cap: "Mid Cap" },
  { symbol: "KEI", name: "KEI Industries Ltd", sector: "Cables", cap: "Mid Cap" },
  { symbol: "FINCABLES", name: "Finolex Cables Ltd", sector: "Cables", cap: "Mid Cap" },
  { symbol: "FINPIPE", name: "Finolex Industries Ltd", sector: "Plastics", cap: "Mid Cap" },
  { symbol: "GREENPANEL", name: "Greenpanel Industries Ltd", sector: "Building Materials", cap: "Mid Cap" },
  { symbol: "GARFIBRES", name: "Garware Technical Fibres", sector: "Textiles", cap: "Mid Cap" },
  { symbol: "GPPL", name: "Gujarat Pipavav Port Ltd", sector: "Logistics", cap: "Mid Cap" },
  { symbol: "GESHIP", name: "Great Eastern Shipping Co", sector: "Logistics", cap: "Mid Cap" },
  { symbol: "ALLCARGO", name: "Allcargo Logistics Ltd", sector: "Logistics", cap: "Mid Cap" },
  { symbol: "AEGISCHEM", name: "Aegis Logistics Ltd", sector: "Logistics", cap: "Mid Cap" },
  { symbol: "AIAENG", name: "AIA Engineering Ltd", sector: "Engineering", cap: "Mid Cap" },
  { symbol: "3MINDIA", name: "3M India Ltd", sector: "Diversified", cap: "Mid Cap" },
  { symbol: "ABCAPITAL", name: "Aditya Birla Capital Ltd", sector: "Finance", cap: "Mid Cap" },
  { symbol: "ABSLAMC", name: "Aditya Birla Sun Life AMC", sector: "Finance", cap: "Mid Cap" },
  { symbol: "AJANTPHARM", name: "Ajanta Pharma Ltd", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "AKZOINDIA", name: "Akzo Nobel India Ltd", sector: "Paints", cap: "Mid Cap" },
  { symbol: "AMARAJABAT", name: "Amara Raja Energy & Mobility", sector: "Auto Ancillary", cap: "Mid Cap" },
  { symbol: "AMBER", name: "Amber Enterprises India", sector: "Consumer Durables", cap: "Mid Cap" },
  { symbol: "APLAPOLLO", name: "APL Apollo Tubes Ltd", sector: "Metals", cap: "Mid Cap" },
  { symbol: "APLLTD", name: "Alembic Pharmaceuticals Ltd", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "BAJAJELEC", name: "Bajaj Electricals Ltd", sector: "Consumer Durables", cap: "Mid Cap" },
  { symbol: "BASF", name: "BASF India Ltd", sector: "Chemicals", cap: "Mid Cap" },
  { symbol: "CCL", name: "CCL Products India Ltd", sector: "FMCG", cap: "Mid Cap" },
  { symbol: "CEATLTD", name: "CEAT Ltd", sector: "Auto Ancillary", cap: "Mid Cap" },
  { symbol: "CESC", name: "CESC Ltd", sector: "Power", cap: "Mid Cap" },
  { symbol: "CUB", name: "City Union Bank Ltd", sector: "Banking", cap: "Mid Cap" },
  { symbol: "DALMIABHA", name: "Dalmia Bharat Ltd", sector: "Cement", cap: "Mid Cap" },
  { symbol: "EPL", name: "EPL Ltd", sector: "Packaging", cap: "Mid Cap" },
  { symbol: "FORCEMOT", name: "Force Motors Ltd", sector: "Auto", cap: "Mid Cap" },
  { symbol: "GILLETTE", name: "Gillette India Ltd", sector: "FMCG", cap: "Mid Cap" },
  { symbol: "GODREJAGRO", name: "Godrej Agrovet Ltd", sector: "FMCG", cap: "Mid Cap" },
  { symbol: "GODREJIND", name: "Godrej Industries Ltd", sector: "Diversified", cap: "Mid Cap" },
  { symbol: "GOCOLORS", name: "Go Fashion India Ltd", sector: "Retail", cap: "Mid Cap" },
  { symbol: "GSPL", name: "Gujarat State Petronet Ltd", sector: "Oil & Gas", cap: "Mid Cap" },
  { symbol: "HATSUN", name: "Hatsun Agro Product Ltd", sector: "FMCG", cap: "Mid Cap" },
  { symbol: "HEG", name: "HEG Ltd", sector: "Chemicals", cap: "Mid Cap" },
  { symbol: "HINDWAREAP", name: "Hindware Home Innovation", sector: "Building Materials", cap: "Mid Cap" },
  { symbol: "HONASA", name: "Honasa Consumer Ltd", sector: "FMCG", cap: "Mid Cap" },
  { symbol: "IDBI", name: "IDBI Bank Ltd", sector: "Banking", cap: "Mid Cap" },
  { symbol: "IEX", name: "Indian Energy Exchange Ltd", sector: "Power", cap: "Mid Cap" },
  { symbol: "IGL", name: "Indraprastha Gas Ltd", sector: "Oil & Gas", cap: "Mid Cap" },
  { symbol: "INDIANB", name: "Indian Bank", sector: "Banking", cap: "Mid Cap" },
  { symbol: "IOB", name: "Indian Overseas Bank", sector: "Banking", cap: "Mid Cap" },
  { symbol: "JKLAKSHMI", name: "JK Lakshmi Cement Ltd", sector: "Cement", cap: "Mid Cap" },
  { symbol: "JKPAPER", name: "JK Paper Ltd", sector: "Paper", cap: "Mid Cap" },
  { symbol: "JSL", name: "Jindal Stainless Ltd", sector: "Metals", cap: "Mid Cap" },
  { symbol: "JSLHISAR", name: "Jindal Stainless Hisar", sector: "Metals", cap: "Mid Cap" },
  { symbol: "JSWENERGY", name: "JSW Energy Ltd", sector: "Power", cap: "Mid Cap" },
  { symbol: "JSWISPL", name: "JSW Infrastructure Ltd", sector: "Infrastructure", cap: "Mid Cap" },
  { symbol: "JYOTHYLAB", name: "Jyothy Labs Ltd", sector: "FMCG", cap: "Mid Cap" },
  { symbol: "KAYNES", name: "Kaynes Technology India", sector: "Electronics", cap: "Mid Cap" },
  { symbol: "KEC", name: "KEC International Ltd", sector: "Infrastructure", cap: "Mid Cap" },
  { symbol: "KNRCON", name: "KNR Constructions Ltd", sector: "Infrastructure", cap: "Mid Cap" },
  { symbol: "KPIL", name: "Kalpataru Projects International", sector: "Infrastructure", cap: "Mid Cap" },
  { symbol: "KSCL", name: "Kaveri Seed Company Ltd", sector: "Agro", cap: "Mid Cap" },
  { symbol: "L&TFH", name: "L&T Finance Holdings", sector: "Finance", cap: "Mid Cap" },
  { symbol: "LINDEINDIA", name: "Linde India Ltd", sector: "Chemicals", cap: "Mid Cap" },
  { symbol: "LLOYDSME", name: "Lloyds Metals And Energy", sector: "Metals", cap: "Mid Cap" },
  { symbol: "M&MFIN", name: "Mahindra & Mahindra Financial Services", sector: "Finance", cap: "Mid Cap" },
  { symbol: "MAHABANK", name: "Bank of Maharashtra", sector: "Banking", cap: "Mid Cap" },
  { symbol: "MFSL", name: "Max Financial Services", sector: "Insurance", cap: "Mid Cap" },
  { symbol: "MGL", name: "Mahanagar Gas Ltd", sector: "Oil & Gas", cap: "Mid Cap" },
  { symbol: "MINDACORP", name: "Minda Corporation Ltd", sector: "Auto Ancillary", cap: "Mid Cap" },
  { symbol: "MRPL", name: "Mangalore Refinery & Petrochemicals", sector: "Oil & Gas", cap: "Mid Cap" },
  { symbol: "FIRSTCRY", name: "Brainbees Solutions Ltd", sector: "Retail", cap: "Mid Cap" },
  
  // ============= SMALL CAP STOCKS (Nifty Smallcap 250 + Additional) =============
  { symbol: "ROUTE", name: "Route Mobile Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "TANLA", name: "Tanla Platforms Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "RBLBANK", name: "RBL Bank Ltd", sector: "Banking", cap: "Small Cap" },
  { symbol: "NATIONALUM", name: "National Aluminium Co", sector: "Metals", cap: "Small Cap" },
  { symbol: "IRFC", name: "Indian Railway Finance Corp", sector: "Finance", cap: "Small Cap" },
  { symbol: "RVNL", name: "Rail Vikas Nigam Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "NHPC", name: "NHPC Ltd", sector: "Power", cap: "Small Cap" },
  { symbol: "IDEA", name: "Vodafone Idea Ltd", sector: "Telecom", cap: "Small Cap" },
  { symbol: "PAYTM", name: "One97 Communications Ltd", sector: "Fintech", cap: "Small Cap" },
  { symbol: "NYKAA", name: "FSN E-Commerce Ventures", sector: "Internet", cap: "Small Cap" },
  { symbol: "POLICYBZR", name: "PB Fintech Ltd", sector: "Fintech", cap: "Small Cap" },
  { symbol: "CARTRADE", name: "CarTrade Tech Ltd", sector: "Internet", cap: "Small Cap" },
  { symbol: "DELTACORP", name: "Delta Corp Ltd", sector: "Gaming", cap: "Small Cap" },
  { symbol: "WELCORP", name: "Welspun Corp Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "WOCKPHARMA", name: "Wockhardt Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "RAJESHEXPO", name: "Rajesh Exports Ltd", sector: "Gems & Jewellery", cap: "Small Cap" },
  { symbol: "AARTIIND", name: "Aarti Industries Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "TATACHEM", name: "Tata Chemicals Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "MAHINDCIE", name: "Mahindra CIE Automotive", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "BIRLACORPN", name: "Birla Corporation Ltd", sector: "Cement", cap: "Small Cap" },
  { symbol: "CENTURYTEX", name: "Century Textiles & Industries", sector: "Textiles", cap: "Small Cap" },
  { symbol: "CENTURYPLY", name: "Century Plyboards India", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "CANFINHOME", name: "Can Fin Homes Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "VGUARD", name: "V-Guard Industries Ltd", sector: "Consumer Durables", cap: "Small Cap" },
  { symbol: "BALAMINES", name: "Balaji Amines Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "IDFC", name: "IDFC Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "IFCI", name: "IFCI Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "IBREALEST", name: "Indiabulls Real Estate", sector: "Real Estate", cap: "Small Cap" },
  { symbol: "SOBHA", name: "Sobha Ltd", sector: "Real Estate", cap: "Small Cap" },
  { symbol: "SUNTV", name: "Sun TV Network Ltd", sector: "Media", cap: "Small Cap" },
  { symbol: "TV18BRDCST", name: "TV18 Broadcast Ltd", sector: "Media", cap: "Small Cap" },
  { symbol: "PVRINOX", name: "PVR INOX Ltd", sector: "Media", cap: "Small Cap" },
  { symbol: "NCC", name: "NCC Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "TEJASNET", name: "Tejas Networks Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "MMTC", name: "MMTC Ltd", sector: "Trading", cap: "Small Cap" },
  { symbol: "MOIL", name: "MOIL Ltd", sector: "Mining", cap: "Small Cap" },
  { symbol: "HFCL", name: "HFCL Ltd", sector: "Telecom", cap: "Small Cap" },
  { symbol: "HEIDELBERG", name: "Heidelberg Cement India", sector: "Cement", cap: "Small Cap" },
  { symbol: "NAVINFLUOR", name: "Navin Fluorine Intl", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "ORIENTELEC", name: "Orient Electric Ltd", sector: "Consumer Durables", cap: "Small Cap" },
  { symbol: "ORIENTCEM", name: "Orient Cement Ltd", sector: "Cement", cap: "Small Cap" },
  { symbol: "PRAJIND", name: "Praj Industries Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "PTC", name: "PTC India Ltd", sector: "Power", cap: "Small Cap" },
  { symbol: "QUESS", name: "Quess Corp Ltd", sector: "Staffing", cap: "Small Cap" },
  { symbol: "RAIN", name: "Rain Industries Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "RALLIS", name: "Rallis India Ltd", sector: "Agro Chemicals", cap: "Small Cap" },
  { symbol: "RCF", name: "Rashtriya Chemicals & Fertilizers", sector: "Fertilizers", cap: "Small Cap" },
  { symbol: "REDINGTON", name: "Redington India Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "SCI", name: "Shipping Corporation of India", sector: "Logistics", cap: "Small Cap" },
  { symbol: "SJVN", name: "SJVN Ltd", sector: "Power", cap: "Small Cap" },
  { symbol: "SRF", name: "SRF Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "SYMPHONY", name: "Symphony Ltd", sector: "Consumer Durables", cap: "Small Cap" },
  { symbol: "TATAINVEST", name: "Tata Investment Corporation", sector: "Finance", cap: "Small Cap" },
  { symbol: "TATAMETALI", name: "Tata Metaliks Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "TEAMLEASE", name: "TeamLease Services Ltd", sector: "Staffing", cap: "Small Cap" },
  { symbol: "TORNTPOWER", name: "Torrent Power Ltd", sector: "Power", cap: "Small Cap" },
  { symbol: "TRIDENT", name: "Trident Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "UFLEX", name: "Uflex Ltd", sector: "Packaging", cap: "Small Cap" },
  { symbol: "UJJIVAN", name: "Ujjivan Financial Services", sector: "Finance", cap: "Small Cap" },
  { symbol: "UJJIVANSFB", name: "Ujjivan Small Finance Bank", sector: "Banking", cap: "Small Cap" },
  { symbol: "UCOBANK", name: "UCO Bank", sector: "Banking", cap: "Small Cap" },
  { symbol: "VTL", name: "Vardhman Textiles Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "WABAG", name: "VA Tech Wabag Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "WELSPUNIND", name: "Welspun India Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "WESTLIFE", name: "Westlife Foodworld Ltd", sector: "QSR", cap: "Small Cap" },
  { symbol: "YESBANK", name: "Yes Bank Ltd", sector: "Banking", cap: "Small Cap" },
  { symbol: "ZENSARTECH", name: "Zensar Technologies Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "ECLERX", name: "eClerx Services Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "GRAPHITE", name: "Graphite India Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "GULFOILLUB", name: "Gulf Oil Lubricants India", sector: "Oil & Gas", cap: "Small Cap" },
  { symbol: "GMDCLTD", name: "Gujarat Mineral Development", sector: "Mining", cap: "Small Cap" },
  { symbol: "GRANULES", name: "Granules India Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "GREENPLY", name: "Greenply Industries Ltd", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "CERA", name: "Cera Sanitaryware Ltd", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "KPRMILL", name: "KPR Mill Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "KSB", name: "KSB Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "LEMONTREE", name: "Lemon Tree Hotels Ltd", sector: "Hotels", cap: "Small Cap" },
  { symbol: "LUXIND", name: "Lux Industries Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "MAITHANALL", name: "Maithan Alloys Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "MARKSANS", name: "Marksans Pharma Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "MAYURUNIQ", name: "Mayur Uniquoters Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "MIDHANI", name: "Mishra Dhatu Nigam Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "MOREPENLAB", name: "Morepen Laboratories Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "NAM-INDIA", name: "Nippon Life India Asset Management", sector: "Finance", cap: "Small Cap" },
  { symbol: "NBCC", name: "NBCC India Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "NFL", name: "National Fertilizers Ltd", sector: "Fertilizers", cap: "Small Cap" },
  { symbol: "NH", name: "Narayana Hrudayalaya Ltd", sector: "Healthcare", cap: "Small Cap" },
  { symbol: "NILKAMAL", name: "Nilkamal Ltd", sector: "Plastics", cap: "Small Cap" },
  { symbol: "NLCINDIA", name: "NLC India Ltd", sector: "Power", cap: "Small Cap" },
  { symbol: "NOCIL", name: "NOCIL Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "OFSS", name: "Oracle Financial Services", sector: "IT", cap: "Small Cap" },
  { symbol: "OIL", name: "Oil India Ltd", sector: "Oil & Gas", cap: "Small Cap" },
  { symbol: "OLECTRA", name: "Olectra Greentech Ltd", sector: "Auto", cap: "Small Cap" },
  { symbol: "PNCINFRA", name: "PNC Infratech Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "PRINCEPIPE", name: "Prince Pipes And Fittings", sector: "Plastics", cap: "Small Cap" },
  { symbol: "PSB", name: "Punjab & Sind Bank", sector: "Banking", cap: "Small Cap" },
  { symbol: "QUICKHEAL", name: "Quick Heal Technologies", sector: "IT", cap: "Small Cap" },
  { symbol: "RAMCOCEM", name: "Ramco Cements Ltd", sector: "Cement", cap: "Small Cap" },
  { symbol: "RATEGAIN", name: "RateGain Travel Technologies", sector: "IT", cap: "Small Cap" },
  { symbol: "RAYMOND", name: "Raymond Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "RITES", name: "RITES Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "SANOFI", name: "Sanofi India Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "SASKEN", name: "Sasken Technologies Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "SCHAEFFLER", name: "Schaeffler India Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "SCHNEIDER", name: "Schneider Electric Infrastructure", sector: "Power", cap: "Small Cap" },
  { symbol: "SHARDACROP", name: "Sharda Cropchem Ltd", sector: "Agro Chemicals", cap: "Small Cap" },
  { symbol: "SIS", name: "SIS Ltd", sector: "Security", cap: "Small Cap" },
  { symbol: "SNOWMAN", name: "Snowman Logistics Ltd", sector: "Logistics", cap: "Small Cap" },
  { symbol: "SOLARINDS", name: "Solar Industries India", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "SOMANYCERA", name: "Somany Ceramics Ltd", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "SPARC", name: "Sun Pharma Advanced Research", sector: "Pharma", cap: "Small Cap" },
  { symbol: "SPICEJET", name: "SpiceJet Ltd", sector: "Aviation", cap: "Small Cap" },
  { symbol: "STLTECH", name: "Sterlite Technologies Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "SUDARSCHEM", name: "Sudarshan Chemical Industries", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "SUMICHEM", name: "Sumitomo Chemical India", sector: "Agro Chemicals", cap: "Small Cap" },
  { symbol: "SWARAJENG", name: "Swaraj Engines Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "TBZ", name: "Tribhovandas Bhimji Zaveri", sector: "Gems & Jewellery", cap: "Small Cap" },
  { symbol: "TCI", name: "Transport Corporation of India", sector: "Logistics", cap: "Small Cap" },
  { symbol: "THYROCARE", name: "Thyrocare Technologies Ltd", sector: "Healthcare", cap: "Small Cap" },
  { symbol: "TINPLATE", name: "Tinplate Company of India", sector: "Metals", cap: "Small Cap" },
  { symbol: "TNPL", name: "Tamil Nadu Newsprint & Papers", sector: "Paper", cap: "Small Cap" },
  { symbol: "TTKPRESTIG", name: "TTK Prestige Ltd", sector: "Consumer Durables", cap: "Small Cap" },
  { symbol: "TVTODAY", name: "TV Today Network Ltd", sector: "Media", cap: "Small Cap" },
  { symbol: "TWL", name: "Titagarh Rail Systems Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "UTIAMC", name: "UTI Asset Management Company", sector: "Finance", cap: "Small Cap" },
  { symbol: "VAIBHAVGBL", name: "Vaibhav Global Ltd", sector: "Gems & Jewellery", cap: "Small Cap" },
  { symbol: "VAKRANGEE", name: "Vakrangee Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "VENKEYS", name: "Venky's India Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "VESUVIUS", name: "Vesuvius India Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "VINATIORGA", name: "Vinati Organics Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "VIPIND", name: "VIP Industries Ltd", sector: "Consumer Durables", cap: "Small Cap" },
  { symbol: "VMART", name: "V-Mart Retail Ltd", sector: "Retail", cap: "Small Cap" },
  { symbol: "VOLTAMP", name: "Voltamp Transformers Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "VRL", name: "VRL Logistics Ltd", sector: "Logistics", cap: "Small Cap" },
  { symbol: "VSTIND", name: "VST Industries Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "WELENT", name: "Welspun Enterprises Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "WONDERLA", name: "Wonderla Holidays Ltd", sector: "Entertainment", cap: "Small Cap" },
  { symbol: "WSTCSTPAPR", name: "West Coast Paper Mills", sector: "Paper", cap: "Small Cap" },
  { symbol: "ZEEL", name: "Zee Entertainment Enterprises", sector: "Media", cap: "Small Cap" },
  { symbol: "J&KBANK", name: "Jammu & Kashmir Bank", sector: "Banking", cap: "Small Cap" },
  { symbol: "JAGRAN", name: "Jagran Prakashan Ltd", sector: "Media", cap: "Small Cap" },
  { symbol: "JAMNAAUTO", name: "Jamna Auto Industries", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "JBMA", name: "JBM Auto Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "JINDALSAW", name: "Jindal Saw Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "JKIL", name: "J. Kumar Infraprojects Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "JKTYRE", name: "JK Tyre & Industries Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "JMFINANCIL", name: "JM Financial Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "JPPOWER", name: "Jaiprakash Power Ventures", sector: "Power", cap: "Small Cap" },
  { symbol: "JSWHL", name: "JSW Holdings Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "JUBLINDS", name: "Jubilant Industries Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "KARURVYSYA", name: "Karur Vysya Bank", sector: "Banking", cap: "Small Cap" },
  { symbol: "KDDL", name: "KDDL Ltd", sector: "Consumer Goods", cap: "Small Cap" },
  { symbol: "KESORAMIND", name: "Kesoram Industries Ltd", sector: "Cement", cap: "Small Cap" },
  { symbol: "KIRLOSENG", name: "Kirloskar Oil Engines Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "KOLTEPATIL", name: "Kolte-Patil Developers", sector: "Real Estate", cap: "Small Cap" },
  { symbol: "KRBL", name: "KRBL Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "LAOPALA", name: "La Opala RG Ltd", sector: "Consumer Goods", cap: "Small Cap" },
  { symbol: "LGBBROSLTD", name: "LG Balakrishnan & Bros", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "LINCOLN", name: "Lincoln Pharmaceuticals", sector: "Pharma", cap: "Small Cap" },
  { symbol: "LLOYDSENGG", name: "Lloyds Engineering Works", sector: "Engineering", cap: "Small Cap" },
  { symbol: "LOKESHMACH", name: "Lokesh Machines Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "MAHLOG", name: "Mahindra Logistics Ltd", sector: "Logistics", cap: "Small Cap" },
  { symbol: "MAHSCOOTER", name: "Maharashtra Scooters Ltd", sector: "Auto", cap: "Small Cap" },
  { symbol: "MAHSEAMLES", name: "Maharashtra Seamless Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "MANALIPETC", name: "Manali Petrochemicals", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "MANGALAM", name: "Mangalam Drugs & Organics", sector: "Pharma", cap: "Small Cap" },
  { symbol: "MANGLMCEM", name: "Mangalam Cement Ltd", sector: "Cement", cap: "Small Cap" },
  { symbol: "MANINDS", name: "Man Industries India Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "MANINFRA", name: "Man Infraconstruction Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "MATRIMONY", name: "Matrimony.com Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "MAWANASUG", name: "Mawana Sugars Ltd", sector: "Sugar", cap: "Small Cap" },
  { symbol: "MAXINDIA", name: "Max India Ltd", sector: "Healthcare", cap: "Small Cap" },
  { symbol: "MBLINFRA", name: "MBL Infrastructures Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "MEGASOFT", name: "Megasoft Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "MEGH", name: "Meghmani Organics Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "MOLDTKPAC", name: "Mold-Tek Packaging Ltd", sector: "Packaging", cap: "Small Cap" },
  { symbol: "MONTECARLO", name: "Monte Carlo Fashions Ltd", sector: "Retail", cap: "Small Cap" },
  { symbol: "MORARJEE", name: "Morarjee Textiles Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "MPSLTD", name: "MPS Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "MSTCLTD", name: "MSTC Ltd", sector: "Trading", cap: "Small Cap" },
  { symbol: "MTARTECH", name: "MTAR Technologies Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "MTNL", name: "Mahanagar Telephone Nigam", sector: "Telecom", cap: "Small Cap" },
  { symbol: "MUKANDLTD", name: "Mukand Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "MURUDCERA", name: "Murudeshwar Ceramics Ltd", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "EASEMYTRIP", name: "Easy Trip Planners Ltd", sector: "Travel", cap: "Small Cap" },
  { symbol: "EDELWEISS", name: "Edelweiss Financial Services", sector: "Finance", cap: "Small Cap" },
  { symbol: "ELECTCAST", name: "Electrosteel Castings Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "ELECON", name: "Elecon Engineering Company", sector: "Engineering", cap: "Small Cap" },
  { symbol: "ESTER", name: "Ester Industries Ltd", sector: "Packaging", cap: "Small Cap" },
  { symbol: "EVERESTIND", name: "Everest Industries Ltd", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "EXCEL", name: "Excel Industries Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "FACT", name: "Fertilisers And Chemicals Travancore", sector: "Fertilizers", cap: "Small Cap" },
  { symbol: "FCL", name: "Fineotex Chemical Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "GABRIEL", name: "Gabriel India Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "GALAXYSURF", name: "Galaxy Surfactants Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "GATEWAY", name: "Gateway Distriparks Ltd", sector: "Logistics", cap: "Small Cap" },
  { symbol: "GENESYS", name: "Genesys International Corp", sector: "IT", cap: "Small Cap" },
  { symbol: "GENUSPOWER", name: "Genus Power Infrastructures", sector: "Engineering", cap: "Small Cap" },
  { symbol: "GEOJITFSL", name: "Geojit Financial Services", sector: "Finance", cap: "Small Cap" },
  { symbol: "GHCL", name: "GHCL Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "GICHSGFIN", name: "GIC Housing Finance Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "GOKALDAS", name: "Gokaldas Exports Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "GOLDIAM", name: "Goldiam International Ltd", sector: "Gems & Jewellery", cap: "Small Cap" },
  { symbol: "GOODLUCK", name: "Goodluck India Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "GOODYEAR", name: "Goodyear India Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "GPIL", name: "Godawari Power & Ispat Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "GRAVITA", name: "Gravita India Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "GREAVESCOT", name: "Greaves Cotton Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "GTL", name: "GTL Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "GUFICBIO", name: "Gufic Biosciences Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "HATHWAY", name: "Hathway Cable & Datacom", sector: "Media", cap: "Small Cap" },
  { symbol: "HAWKINCOOK", name: "Hawkins Cookers Ltd", sector: "Consumer Durables", cap: "Small Cap" },
  { symbol: "HBLPOWER", name: "HBL Power Systems Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "HCC", name: "Hindustan Construction Co", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "HCG", name: "Healthcare Global Enterprises", sector: "Healthcare", cap: "Small Cap" },
  { symbol: "HERANBA", name: "Heranba Industries Ltd", sector: "Agro Chemicals", cap: "Small Cap" },
  { symbol: "HERCULES", name: "Hercules Hoists Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "HERITGFOOD", name: "Heritage Foods Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "HESTERBIO", name: "Hester Biosciences Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "HGINFRA", name: "H.G. Infra Engineering Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "HIKAL", name: "Hikal Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "HIL", name: "HIL Ltd", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "HILTON", name: "Hilton Metal Forging Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "HIMATSEIDE", name: "Himatsingka Seide Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "HINDMOTORS", name: "Hindustan Motors Ltd", sector: "Auto", cap: "Small Cap" },
  { symbol: "HINDNATGLS", name: "Hindusthan National Glass", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "HINDOILEXP", name: "Hindustan Oil Exploration Co", sector: "Oil & Gas", cap: "Small Cap" },
  { symbol: "HIRECT", name: "Hind Rectifiers Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "HLEGLAS", name: "HLE Glascoat Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "HMVL", name: "Hindustan Media Ventures", sector: "Media", cap: "Small Cap" },
  { symbol: "HONDAPOWER", name: "Honda India Power Products", sector: "Engineering", cap: "Small Cap" },
  { symbol: "HSCL", name: "Himadri Speciality Chemical", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "HSIL", name: "HSIL Ltd", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "HTMEDIA", name: "HT Media Ltd", sector: "Media", cap: "Small Cap" },
  { symbol: "HUHTAMAKI", name: "Huhtamaki India Ltd", sector: "Packaging", cap: "Small Cap" },
  { symbol: "ICRA", name: "ICRA Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "IFBIND", name: "IFB Industries Ltd", sector: "Consumer Durables", cap: "Small Cap" },
  { symbol: "IGARASHI", name: "Igarashi Motors India Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "IGPL", name: "IG Petrochemicals Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "IIFLSEC", name: "IIFL Securities Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "IMFA", name: "Indian Metals & Ferro Alloys", sector: "Metals", cap: "Small Cap" },
  { symbol: "INDIACEM", name: "The India Cements Ltd", sector: "Cement", cap: "Small Cap" },
  { symbol: "INDIAGLYCO", name: "India Glycols Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "INDIANHUME", name: "Indian Hume Pipe Co Ltd", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "INDNIPPON", name: "India Nippon Electricals", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "INDOCO", name: "Indoco Remedies Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "INDORAMA", name: "Indo Rama Synthetics India", sector: "Textiles", cap: "Small Cap" },
  { symbol: "INDOSTAR", name: "IndoStar Capital Finance", sector: "Finance", cap: "Small Cap" },
  { symbol: "INDOTECH", name: "Indo Tech Transformers", sector: "Engineering", cap: "Small Cap" },
  { symbol: "INDRAMEDCO", name: "Indraprastha Medical Corp", sector: "Healthcare", cap: "Small Cap" },
  { symbol: "INFIBEAM", name: "Infibeam Avenues Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "INGERRAND", name: "Ingersoll-Rand India Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "INOXGREEN", name: "Inox Green Energy Services", sector: "Power", cap: "Small Cap" },
  { symbol: "INOXWIND", name: "Inox Wind Ltd", sector: "Power", cap: "Small Cap" },
  { symbol: "INSECTICID", name: "Insecticides India Ltd", sector: "Agro Chemicals", cap: "Small Cap" },
  { symbol: "ITDC", name: "India Tourism Dev Corp", sector: "Hotels", cap: "Small Cap" },
  { symbol: "ITI", name: "ITI Ltd", sector: "Telecom", cap: "Small Cap" },
  { symbol: "IVP", name: "IVP Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "BAJAJCON", name: "Bajaj Consumer Care Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "BAJAJHIND", name: "Bajaj Hindusthan Sugar Ltd", sector: "Sugar", cap: "Small Cap" },
  { symbol: "BALRAMCHIN", name: "Balrampur Chini Mills Ltd", sector: "Sugar", cap: "Small Cap" },
  { symbol: "BANARISUG", name: "Bannari Amman Sugars Ltd", sector: "Sugar", cap: "Small Cap" },
  { symbol: "BANCOINDIA", name: "Banco Products India Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "BANG", name: "Bang Overseas Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "BBTC", name: "Bombay Burmah Trading Corp", sector: "Diversified", cap: "Small Cap" },
  { symbol: "BBL", name: "Bharat Bijlee Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "BCG", name: "Brightcom Group Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "BFINVEST", name: "BF Investment Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "BFUTILITIE", name: "BF Utilities Ltd", sector: "Power", cap: "Small Cap" },
  { symbol: "BHAGERIA", name: "Bhageria Industries Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "BHARATRAS", name: "Bharat Rasayan Ltd", sector: "Agro Chemicals", cap: "Small Cap" },
  { symbol: "BIL", name: "Bhartiya International Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "BIGBLOC", name: "Bigbloc Construction Ltd", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "BLS", name: "BLS International Services", sector: "IT", cap: "Small Cap" },
  { symbol: "BODALCHEM", name: "Bodal Chemicals Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "BOMDYEING", name: "Bombay Dyeing & Mfg Co", sector: "Textiles", cap: "Small Cap" },
  { symbol: "BOROLTD", name: "Borosil Ltd", sector: "Consumer Goods", cap: "Small Cap" },
  { symbol: "BORORENEW", name: "Borosil Renewables Ltd", sector: "Power", cap: "Small Cap" },
  { symbol: "BSL", name: "BSL Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "CAMLINFINE", name: "Camlin Fine Sciences Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "CANTABIL", name: "Cantabil Retail India Ltd", sector: "Retail", cap: "Small Cap" },
  { symbol: "CAPACITE", name: "Capacit'e Infraprojects", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "CARERATING", name: "CARE Ratings Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "CARYSIL", name: "Carysil Ltd", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "CENTUM", name: "Centum Electronics Ltd", sector: "Electronics", cap: "Small Cap" },
  { symbol: "CHEMCON", name: "Chemcon Speciality Chemicals", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "CHENNPETRO", name: "Chennai Petroleum Corp", sector: "Oil & Gas", cap: "Small Cap" },
  { symbol: "CIGNITITEC", name: "Cigniti Technologies Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "CLSEL", name: "Chaman Lal Setia Exports", sector: "FMCG", cap: "Small Cap" },
  { symbol: "COFFEEDAY", name: "Coffee Day Enterprises", sector: "Retail", cap: "Small Cap" },
  { symbol: "COMPINFO", name: "Compuage Infocom Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "CONFIPET", name: "Confidence Petroleum India", sector: "Oil & Gas", cap: "Small Cap" },
  { symbol: "CONTROLPR", name: "Control Print Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "COSMOFIRST", name: "Cosmo First Ltd", sector: "Packaging", cap: "Small Cap" },
  { symbol: "CSBBANK", name: "CSB Bank Ltd", sector: "Banking", cap: "Small Cap" },
  { symbol: "CUPID", name: "Cupid Ltd", sector: "Healthcare", cap: "Small Cap" },
  { symbol: "DALBHARAT", name: "Dalmia Bharat Sugar & Industries", sector: "Sugar", cap: "Small Cap" },
  { symbol: "DATAMATICS", name: "Datamatics Global Services", sector: "IT", cap: "Small Cap" },
  { symbol: "DBCORP", name: "DB Corp Ltd", sector: "Media", cap: "Small Cap" },
  { symbol: "DBL", name: "Dilip Buildcon Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "DBREALTY", name: "D B Realty Ltd", sector: "Real Estate", cap: "Small Cap" },
  { symbol: "DCAL", name: "Dishman Carbogen Amcis", sector: "Pharma", cap: "Small Cap" },
  { symbol: "DCBBANK", name: "DCB Bank Ltd", sector: "Banking", cap: "Small Cap" },
  { symbol: "DCXINDIA", name: "DCX Systems Ltd", sector: "Defence", cap: "Small Cap" },
  { symbol: "DECCANCE", name: "Deccan Cements Ltd", sector: "Cement", cap: "Small Cap" },
  { symbol: "DEEPAKFERT", name: "Deepak Fertilisers & Petrochemicals", sector: "Fertilizers", cap: "Small Cap" },
  { symbol: "DENORA", name: "De Nora India Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "DHAMPURSUG", name: "Dhampur Sugar Mills Ltd", sector: "Sugar", cap: "Small Cap" },
  { symbol: "DHANUKA", name: "Dhanuka Agritech Ltd", sector: "Agro Chemicals", cap: "Small Cap" },
  { symbol: "DHANI", name: "Dhani Services Ltd", sector: "Fintech", cap: "Small Cap" },
  { symbol: "DISHTV", name: "Dish TV India Ltd", sector: "Media", cap: "Small Cap" },
  { symbol: "DLINKINDIA", name: "D-Link India Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "DOLLAR", name: "Dollar Industries Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "DWARKESH", name: "Dwarikesh Sugar Industries", sector: "Sugar", cap: "Small Cap" },
  { symbol: "DYNPRO", name: "Dynemic Products Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "ACCELYA", name: "Accelya Solutions India", sector: "IT", cap: "Small Cap" },
  { symbol: "ACE", name: "Action Construction Equipment", sector: "Engineering", cap: "Small Cap" },
  { symbol: "ADFFOODS", name: "ADF Foods Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "ADORWELD", name: "Ador Welding Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "ADVENZYMES", name: "Advanced Enzyme Technologies", sector: "Pharma", cap: "Small Cap" },
  { symbol: "AGARIND", name: "Agarwal Industrial Corporation", sector: "Metals", cap: "Small Cap" },
  { symbol: "AHLUCONT", name: "Ahluwalia Contracts India", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "AIRAN", name: "Airan Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "AJMERA", name: "Ajmera Realty & Infra India", sector: "Real Estate", cap: "Small Cap" },
  { symbol: "AKSHOPTFBR", name: "Aksh Optifibre Ltd", sector: "Cables", cap: "Small Cap" },
  { symbol: "ALANKIT", name: "Alankit Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "ALBERTDAVD", name: "Albert David Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "ALEMBICLTD", name: "Alembic Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "ALICON", name: "Alicon Castalloy Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "ALKALI", name: "Alkali Metals Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "ALLSEC", name: "Allsec Technologies Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "ALPHAGEO", name: "Alphageo India Ltd", sector: "Oil & Gas", cap: "Small Cap" },
  { symbol: "AMBIKCO", name: "Ambika Cotton Mills Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "AMDIND", name: "AMD Industries Ltd", sector: "Packaging", cap: "Small Cap" },
  { symbol: "ANANTRAJ", name: "Anant Raj Ltd", sector: "Real Estate", cap: "Small Cap" },
  { symbol: "ANDHRSUGAR", name: "Andhra Sugars Ltd", sector: "Sugar", cap: "Small Cap" },
  { symbol: "ANUP", name: "Anup Engineering Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "APCOTEXIND", name: "Apcotex Industries Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "APEX", name: "Apex Frozen Foods Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "APOLLO", name: "Apollo Micro Systems Ltd", sector: "Defence", cap: "Small Cap" },
  { symbol: "APOLLOPIPE", name: "Apollo Pipes Ltd", sector: "Plastics", cap: "Small Cap" },
  { symbol: "APTECHT", name: "Aptech Ltd", sector: "Education", cap: "Small Cap" },
  { symbol: "ARCHIDPLY", name: "Archidply Industries Ltd", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "ARCHIES", name: "Archies Ltd", sector: "Retail", cap: "Small Cap" },
  { symbol: "ARIHANTCAP", name: "Arihant Capital Markets", sector: "Finance", cap: "Small Cap" },
  { symbol: "ARIHANTSUP", name: "Arihant Superstructures", sector: "Real Estate", cap: "Small Cap" },
  { symbol: "ARMANFIN", name: "Arman Financial Services", sector: "Finance", cap: "Small Cap" },
  { symbol: "ARSHIYA", name: "Arshiya Ltd", sector: "Logistics", cap: "Small Cap" },
  { symbol: "ARTEMISMED", name: "Artemis Medicare Services", sector: "Healthcare", cap: "Small Cap" },
  { symbol: "ARVSMART", name: "Arvind Smartspaces Ltd", sector: "Real Estate", cap: "Small Cap" },
  { symbol: "ARVIND", name: "Arvind Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "ARVINDFASN", name: "Arvind Fashions Ltd", sector: "Retail", cap: "Small Cap" },
  { symbol: "ASAHIINDIA", name: "Asahi India Glass Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "ASHIANA", name: "Ashiana Housing Ltd", sector: "Real Estate", cap: "Small Cap" },
  { symbol: "ASHOKA", name: "Ashoka Buildcon Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "ASTEC", name: "Astec LifeSciences Ltd", sector: "Agro Chemicals", cap: "Small Cap" },
  { symbol: "ASTRAMICRO", name: "Astra Microwave Products", sector: "Defence", cap: "Small Cap" },
  { symbol: "ASTRAZEN", name: "AstraZeneca Pharma India", sector: "Pharma", cap: "Small Cap" },
  { symbol: "ATFL", name: "Agro Tech Foods Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "ATULAUTO", name: "Atul Auto Ltd", sector: "Auto", cap: "Small Cap" },
  { symbol: "AURIONPRO", name: "Aurionpro Solutions Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "AUTOAXLES", name: "Automotive Axles Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "AVANTIFEED", name: "Avanti Feeds Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "AWHCL", name: "Antony Waste Handling Cell", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "AXISCADES", name: "AXISCADES Technologies", sector: "IT", cap: "Small Cap" },
  { symbol: "AADHARHFC", name: "Aadhar Housing Finance Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "AARTIDRUGS", name: "Aarti Drugs Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "AARTISURF", name: "Aarti Surfactants Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "FINOPB", name: "Fino Payments Bank Ltd", sector: "Banking", cap: "Small Cap" },
  { symbol: "FMGOETZE", name: "Federal-Mogul Goetze India", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "FOSECOIND", name: "Foseco India Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "GANECOS", name: "Ganesha Ecosphere Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "GFLLIMITED", name: "GFL Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "GNA", name: "GNA Axles Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "GOACARBON", name: "Goa Carbon Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "GLOBUSSPR", name: "Globus Spirits Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "GMBREW", name: "GM Breweries Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "GRMOVER", name: "GRM Overseas Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "KIRIINDUS", name: "Kiri Industries Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "KITEX", name: "Kitex Garments Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "KOPRAN", name: "Kopran Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "KSOLVES", name: "Ksolves India Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "KUANTUM", name: "Kuantum Papers Ltd", sector: "Paper", cap: "Small Cap" },
  { symbol: "LIKHITHA", name: "Likhitha Infrastructure", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "LYKALABS", name: "Lyka Labs Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "MMFL", name: "MM Forgings Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "MOLDTECH", name: "Mold-Tek Technologies Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "GALLANTT", name: "Gallantt Ispat Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "GANESHHOUC", name: "Ganesh Housing Corp Ltd", sector: "Real Estate", cap: "Small Cap" },
  { symbol: "HAPPYFORGE", name: "Happy Forgings Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "HARIOMPIPE", name: "Hariom Pipe Industries Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "HARRMALAYA", name: "Harrisons Malayalam Ltd", sector: "Agro", cap: "Small Cap" },
  { symbol: "HEMIPROP", name: "Hemisphere Properties India", sector: "Real Estate", cap: "Small Cap" },
  { symbol: "HISARMETAL", name: "Hisar Metal Industries Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "HITECHGEAR", name: "The Hi-Tech Gears Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "ICEMAKE", name: "Ice Make Refrigeration Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "INDSWFTLAB", name: "Ind-Swift Laboratories Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "ISFT", name: "Intrasoft Technologies Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "JAIBALAJI", name: "Jai Balaji Industries Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "JAICORPLTD", name: "Jai Corp Ltd", sector: "Diversified", cap: "Small Cap" },
  { symbol: "JASH", name: "Jash Engineering Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "JAYNECOIND", name: "Jayaswal Neco Industries", sector: "Metals", cap: "Small Cap" },
  { symbol: "JHS", name: "JHS Svendgaard Laboratories", sector: "FMCG", cap: "Small Cap" },
  { symbol: "JINDALPOLY", name: "Jindal Poly Films Ltd", sector: "Packaging", cap: "Small Cap" },
  { symbol: "JISLJALEQS", name: "Jain Irrigation Systems", sector: "Agro", cap: "Small Cap" },
  { symbol: "JMCPROJECT", name: "JMC Projects India Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "JOCIL", name: "Jocil Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "JPASSOCIAT", name: "Jaiprakash Associates Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "JPOLYINVST", name: "Jindal Poly Investment & Finance", sector: "Finance", cap: "Small Cap" },
  { symbol: "JTEKTINDIA", name: "JTEKT India Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "JUNIPER", name: "Juniper Hotels Ltd", sector: "Hotels", cap: "Small Cap" },
  { symbol: "KAMAHOLD", name: "Kamat Hotels India Ltd", sector: "Hotels", cap: "Small Cap" },
  { symbol: "KAMDHENU", name: "Kamdhenu Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "KANORICHEM", name: "Kanoria Chemicals & Industries", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "KAPSTON", name: "Kapston Facilities Management", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "KELLTONTEC", name: "Kellton Tech Solutions", sector: "IT", cap: "Small Cap" },
  { symbol: "KINGFA", name: "Kingfa Science & Technology", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "KIRLOSIND", name: "Kirloskar Industries Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "KMSUGAR", name: "KM Sugar Mills Ltd", sector: "Sugar", cap: "Small Cap" },
  { symbol: "LASA", name: "Lasa Supergenerics Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "SADBHAV", name: "Sadbhav Engineering Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "SARDAEN", name: "Sarda Energy & Minerals", sector: "Power", cap: "Small Cap" },
  { symbol: "SHANKARA", name: "Shankara Building Products", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "SHILPAMED", name: "Shilpa Medicare Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "SHREYAS", name: "Shreyas Shipping & Logistics", sector: "Logistics", cap: "Small Cap" },
  { symbol: "SOLARA", name: "Solara Active Pharma Sciences", sector: "Pharma", cap: "Small Cap" },
  { symbol: "SPANDANA", name: "Spandana Sphoorty Financial", sector: "Finance", cap: "Small Cap" },
  { symbol: "SSWL", name: "Steel Strips Wheels Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "SUBROS", name: "Subros Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "SUNCLAYLTD", name: "Sundaram Clayton Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "SUVEN", name: "Suven Pharmaceuticals Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "TAKE", name: "Take Solutions Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "TASTYBITE", name: "Tasty Bite Eatables Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "TCNSBRANDS", name: "TCNS Clothing Co Ltd", sector: "Retail", cap: "Small Cap" },
  { symbol: "TDPOWERSYS", name: "TD Power Systems Ltd", sector: "Power", cap: "Small Cap" },
  { symbol: "TECHNOE", name: "Techno Electric & Engineering", sector: "Power", cap: "Small Cap" },
  { symbol: "TEXRAIL", name: "Texmaco Rail & Engineering", sector: "Engineering", cap: "Small Cap" },
  { symbol: "THOMASCOOK", name: "Thomas Cook India Ltd", sector: "Travel", cap: "Small Cap" },
  { symbol: "TIIL", name: "Technocraft Industries India", sector: "Engineering", cap: "Small Cap" },
  { symbol: "UFO", name: "UFO Moviez India Ltd", sector: "Media", cap: "Small Cap" },
  { symbol: "UNICHEMLAB", name: "Unichem Laboratories Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "V2RETAIL", name: "V2 Retail Ltd", sector: "Retail", cap: "Small Cap" },
  { symbol: "VALUEIND", name: "Value Industries Ltd", sector: "Consumer Durables", cap: "Small Cap" },
  { symbol: "WINDMACHIN", name: "Windsor Machines Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "XPROINDIA", name: "Xpro India Ltd", sector: "Plastics", cap: "Small Cap" },
  { symbol: "ZENITHSTL", name: "Zenith Steel Pipes & Industries", sector: "Metals", cap: "Small Cap" },
  { symbol: "ZUARI", name: "Zuari Agro Chemicals Ltd", sector: "Fertilizers", cap: "Small Cap" },
  { symbol: "ZUARIGLOB", name: "Zuari Global Ltd", sector: "Diversified", cap: "Small Cap" },
  { symbol: "EMKAY", name: "Emkay Global Financial Services", sector: "Finance", cap: "Small Cap" },
  { symbol: "EROSMEDIA", name: "Eros Media World Plc", sector: "Media", cap: "Small Cap" },
  { symbol: "ESABINDIA", name: "ESAB India Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "ETHOSLTD", name: "Ethos Ltd", sector: "Retail", cap: "Small Cap" },
  { symbol: "DOLATALGO", name: "Dolat Algotech Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "DONEAR", name: "Donear Industries Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "FINOPB", name: "Fino Payments Bank Ltd", sector: "Banking", cap: "Small Cap" },
  { symbol: "GANDHAR", name: "Gandhar Oil Refinery India", sector: "Oil & Gas", cap: "Small Cap" },
  { symbol: "IZMO", name: "IZMO Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "KPIGREEN", name: "KP Energy Ltd", sector: "Power", cap: "Small Cap" },
  { symbol: "RELIGARE", name: "Religare Enterprises Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "STARCEMENT", name: "Star Cement Ltd", sector: "Cement", cap: "Small Cap" },
  { symbol: "JKCEMENT", name: "JK Cement Ltd", sector: "Cement", cap: "Small Cap" },
  { symbol: "TRITURBINE", name: "Triveni Turbine Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "TVSSCS", name: "TVS Supply Chain Solutions", sector: "Logistics", cap: "Small Cap" },
  { symbol: "EQUITAS", name: "Equitas Holdings Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "EQUITASBNK", name: "Equitas Small Finance Bank", sector: "Banking", cap: "Small Cap" },
  { symbol: "EVEREADY", name: "Eveready Industries India", sector: "Consumer Durables", cap: "Small Cap" },
  { symbol: "ENDURANCE", name: "Endurance Technologies Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "EIDPARRY", name: "EID Parry India Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "GDL", name: "Gateway Distriparks Ltd", sector: "Logistics", cap: "Small Cap" },
  { symbol: "RAJRATAN", name: "Rajratan Global Wire Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "STAR", name: "Strides Pharma Science", sector: "Pharma", cap: "Small Cap" },
  { symbol: "LXCHEM", name: "Laxmi Organic Industries", sector: "Chemicals", cap: "Small Cap" },
];

// Helper to generate realistic stock data
function generateStockData(stock: StockSeed) {
  const today = new Date();
  const seed = stock.symbol.split('').reduce((a, b) => a + b.charCodeAt(0), 0) + today.getDate();
  
  const pseudoRandom = (offset: number) => {
    const x = Math.sin(seed + offset) * 10000;
    return x - Math.floor(x);
  };

  // Base price ranges by market cap
  const priceRanges: Record<string, [number, number]> = {
    "Large Cap": [500, 5000],
    "Mid Cap": [200, 2000],
    "Small Cap": [50, 500],
  };

  const range = priceRanges[stock.cap] || [100, 1000];
  const basePrice = range[0] + pseudoRandom(1) * (range[1] - range[0]);
  const currentPrice = Math.round(basePrice * 100) / 100;

  // Change percent (-5% to +5%)
  const changePercent = Math.round((pseudoRandom(2) * 10 - 5) * 100) / 100;
  const previousClose = Math.round((currentPrice / (1 + changePercent / 100)) * 100) / 100;

  // Market cap in crores
  const marketCapMultipliers: Record<string, [number, number]> = {
    "Large Cap": [100000, 2000000],
    "Mid Cap": [10000, 100000],
    "Small Cap": [1000, 10000],
  };
  const capRange = marketCapMultipliers[stock.cap] || [1000, 50000];
  const marketCap = Math.round(capRange[0] + pseudoRandom(3) * (capRange[1] - capRange[0]));

  // 52 week range
  const week52Low = Math.round(currentPrice * (0.6 + pseudoRandom(4) * 0.2) * 100) / 100;
  const week52High = Math.round(currentPrice * (1.1 + pseudoRandom(5) * 0.4) * 100) / 100;

  return {
    symbol: stock.symbol,
    company_name: stock.name,
    exchange: "NSE",
    sector: stock.sector,
    industry: stock.sector,
    market_cap: marketCap,
    market_cap_category: stock.cap,
    current_price: currentPrice,
    previous_close: previousClose,
    change_percent: changePercent,
    day_high: Math.round(currentPrice * (1 + pseudoRandom(6) * 0.03) * 100) / 100,
    day_low: Math.round(currentPrice * (1 - pseudoRandom(7) * 0.03) * 100) / 100,
    week_52_high: week52High,
    week_52_low: week52Low,
    volume: Math.round(100000 + pseudoRandom(8) * 10000000),
    pe_ratio: Math.round((10 + pseudoRandom(9) * 40) * 100) / 100,
    pb_ratio: Math.round((1 + pseudoRandom(10) * 10) * 100) / 100,
    dividend_yield: Math.round(pseudoRandom(11) * 5 * 100) / 100,
    eps: Math.round((currentPrice / (15 + pseudoRandom(12) * 20)) * 100) / 100,
    book_value: Math.round((currentPrice / (1 + pseudoRandom(13) * 5)) * 100) / 100,
    roe: Math.round((5 + pseudoRandom(14) * 25) * 100) / 100,
    roce: Math.round((5 + pseudoRandom(15) * 20) * 100) / 100,
    face_value: [1, 2, 5, 10][Math.floor(pseudoRandom(16) * 4)],
  };
}

// Generate shareholding pattern
function generateShareholding(stockId: string, symbol: string) {
  const seed = symbol.split('').reduce((a, b) => a + b.charCodeAt(0), 0);
  const pseudoRandom = (offset: number) => {
    const x = Math.sin(seed + offset) * 10000;
    return x - Math.floor(x);
  };

  const quarters = [];
  const today = new Date();
  
  for (let i = 0; i < 8; i++) {
    const quarterDate = new Date(today);
    quarterDate.setMonth(quarterDate.getMonth() - i * 3);
    const month = quarterDate.getMonth();
    const quarterEnd = new Date(quarterDate.getFullYear(), Math.floor(month / 3) * 3 + 3, 0);

    const promoter = 35 + pseudoRandom(i * 10 + 1) * 25;
    const fii = 10 + pseudoRandom(i * 10 + 2) * 20;
    const dii = 10 + pseudoRandom(i * 10 + 3) * 15;
    const govt = pseudoRandom(i * 10 + 4) * 5;
    const others = Math.max(0, 100 - promoter - fii - dii - govt);

    quarters.push({
      stock_id: stockId,
      quarter_end_date: quarterEnd.toISOString().split('T')[0],
      promoter_holding: Math.round(promoter * 100) / 100,
      fii_holding: Math.round(fii * 100) / 100,
      dii_holding: Math.round(dii * 100) / 100,
      government_holding: Math.round(govt * 100) / 100,
      retail_holding: Math.round((others * 0.7) * 100) / 100,
      others_holding: Math.round((others * 0.3) * 100) / 100,
    });
  }

  return quarters;
}

// Generate financial data
function generateFinancials(stockId: string, symbol: string, currentPrice: number) {
  const seed = symbol.split('').reduce((a, b) => a + b.charCodeAt(0), 0);
  const pseudoRandom = (offset: number) => {
    const x = Math.sin(seed + offset) * 10000;
    return x - Math.floor(x);
  };

  const financials = [];
  const today = new Date();

  for (let i = 0; i < 12; i++) {
    const quarterDate = new Date(today);
    quarterDate.setMonth(quarterDate.getMonth() - i * 3);
    const month = quarterDate.getMonth();
    const quarterEnd = new Date(quarterDate.getFullYear(), Math.floor(month / 3) * 3 + 3, 0);

    const baseRevenue = 1000 + pseudoRandom(i * 20 + 1) * 50000;
    const growth = 1 + (0.1 - i * 0.01);

    financials.push({
      stock_id: stockId,
      period_type: "quarterly",
      period_end_date: quarterEnd.toISOString().split('T')[0],
      revenue: Math.round(baseRevenue * growth * 100) / 100,
      net_profit: Math.round(baseRevenue * growth * (0.05 + pseudoRandom(i * 20 + 2) * 0.15) * 100) / 100,
      operating_profit: Math.round(baseRevenue * growth * (0.1 + pseudoRandom(i * 20 + 3) * 0.2) * 100) / 100,
      ebitda: Math.round(baseRevenue * growth * (0.15 + pseudoRandom(i * 20 + 4) * 0.15) * 100) / 100,
    });
  }

  return financials;
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Remove duplicates by symbol
    const uniqueStocks = ALL_STOCKS.filter((stock, index, self) => 
      index === self.findIndex(s => s.symbol === stock.symbol)
    );

    console.log(`Starting to seed ${uniqueStocks.length} unique stocks...`);

    let successCount = 0;
    let errorCount = 0;
    const batchSize = 50;

    // Process in batches
    for (let i = 0; i < uniqueStocks.length; i += batchSize) {
      const batch = uniqueStocks.slice(i, i + batchSize);
      console.log(`Processing batch ${Math.floor(i / batchSize) + 1}/${Math.ceil(uniqueStocks.length / batchSize)}`);

      for (const stock of batch) {
        try {
          const stockData = generateStockData(stock);

          const { data: insertedStock, error: stockError } = await supabase
            .from("stocks")
            .upsert(stockData, { onConflict: "symbol" })
            .select("id")
            .single();

          if (stockError) {
            console.error(`Error inserting ${stock.symbol}:`, stockError);
            errorCount++;
            continue;
          }

          if (insertedStock) {
            // Insert shareholding pattern
            const shareholding = generateShareholding(insertedStock.id, stock.symbol);
            for (const sh of shareholding) {
              await supabase
                .from("stock_shareholding")
                .upsert(sh, { onConflict: "stock_id,quarter_end_date" });
            }

            // Insert financial data
            const financials = generateFinancials(insertedStock.id, stock.symbol, stockData.current_price);
            for (const fin of financials) {
              await supabase
                .from("stock_financials")
                .upsert(fin, { onConflict: "stock_id,period_type,period_end_date" });
            }
          }

          successCount++;
        } catch (error) {
          console.error(`Error processing ${stock.symbol}:`, error);
          errorCount++;
        }
      }
    }

    console.log(`Seeding complete: ${successCount} success, ${errorCount} errors`);

    return new Response(
      JSON.stringify({ 
        success: true, 
        message: `Seeded ${successCount} stocks with ${errorCount} errors`,
        total: uniqueStocks.length,
        successCount,
        errorCount 
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("Error in seed-stock-data:", error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
