// Additional stocks for comprehensive NSE + BSE coverage
// This file adds more stocks to reach 2000+ total

export interface StockSeed {
  symbol: string;
  name: string;
  sector: string;
  cap: "Large Cap" | "Mid Cap" | "Small Cap";
}

// More NSE stocks alphabetically organized
export const MORE_NSE_STOCKS: StockSeed[] = [
  // B
  { symbol: "BABAFOOD", name: "Baba Food Processing India", sector: "FMCG", cap: "Small Cap" },
  { symbol: "BAJAJCON", name: "Bajaj Consumer Care Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "BAJAJELEC", name: "Bajaj Electricals Ltd", sector: "Consumer Durables", cap: "Mid Cap" },
  { symbol: "BAJAJHIND", name: "Bajaj Hindusthan Sugar Ltd", sector: "Sugar", cap: "Small Cap" },
  { symbol: "BALRAMCHIN", name: "Balrampur Chini Mills Ltd", sector: "Sugar", cap: "Small Cap" },
  { symbol: "BANARISUG", name: "Bannari Amman Sugars Ltd", sector: "Sugar", cap: "Small Cap" },
  { symbol: "BANARBEADS", name: "Banaras Beads Ltd", sector: "Handicrafts", cap: "Small Cap" },
  { symbol: "BANCOINDIA", name: "Banco Products India Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "BANG", name: "Bang Overseas Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "BASF", name: "BASF India Ltd", sector: "Chemicals", cap: "Mid Cap" },
  { symbol: "BBTC", name: "Bombay Burmah Trading Corp", sector: "Diversified", cap: "Small Cap" },
  { symbol: "BBL", name: "Bharat Bijlee Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "BCG", name: "Brightcom Group Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "BDL", name: "Bharat Dynamics Ltd", sector: "Defence", cap: "Mid Cap" },
  { symbol: "BEML", name: "BEML Ltd", sector: "Engineering", cap: "Mid Cap" },
  { symbol: "BERGEPAINT", name: "Berger Paints India Ltd", sector: "Paints", cap: "Large Cap" },
  { symbol: "BFINVEST", name: "BF Investment Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "BFUTILITIE", name: "BF Utilities Ltd", sector: "Power", cap: "Small Cap" },
  { symbol: "BHAGERIA", name: "Bhageria Industries Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "BHARATRAS", name: "Bharat Rasayan Ltd", sector: "Agro Chemicals", cap: "Small Cap" },
  { symbol: "BHARATWIRE", name: "Bharat Wire Ropes Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "BIL", name: "Bhartiya International Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "BIGBLOC", name: "Bigbloc Construction Ltd", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "BLS", name: "BLS International Services", sector: "IT", cap: "Small Cap" },
  { symbol: "BLUESTARCO", name: "Blue Star Ltd", sector: "Consumer Durables", cap: "Mid Cap" },
  { symbol: "BODALCHEM", name: "Bodal Chemicals Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "BOMDYEING", name: "Bombay Dyeing & Mfg Co", sector: "Textiles", cap: "Small Cap" },
  { symbol: "BOROLTD", name: "Borosil Ltd", sector: "Consumer Goods", cap: "Small Cap" },
  { symbol: "BORORENEW", name: "Borosil Renewables Ltd", sector: "Power", cap: "Small Cap" },
  { symbol: "BRIGADE", name: "Brigade Enterprises Ltd", sector: "Real Estate", cap: "Mid Cap" },
  { symbol: "BSHSL", name: "Bombay Super Hybrid Seeds", sector: "Agro", cap: "Small Cap" },
  { symbol: "BSL", name: "BSL Ltd", sector: "Textiles", cap: "Small Cap" },
  
  // C
  { symbol: "CAMLINFINE", name: "Camlin Fine Sciences Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "CAMPUS", name: "Campus Activewear Ltd", sector: "Footwear", cap: "Mid Cap" },
  { symbol: "CANTABIL", name: "Cantabil Retail India Ltd", sector: "Retail", cap: "Small Cap" },
  { symbol: "CAPACITE", name: "Capacit'e Infraprojects", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "CAPLIPOINT", name: "Caplin Point Laboratories", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "CARERATING", name: "CARE Ratings Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "CARYSIL", name: "Carysil Ltd", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "CCL", name: "CCL Products India Ltd", sector: "FMCG", cap: "Mid Cap" },
  { symbol: "CDSL", name: "Central Depository Services", sector: "Finance", cap: "Mid Cap" },
  { symbol: "CEATLTD", name: "CEAT Ltd", sector: "Auto Ancillary", cap: "Mid Cap" },
  { symbol: "CENTUM", name: "Centum Electronics Ltd", sector: "Electronics", cap: "Small Cap" },
  { symbol: "CESC", name: "CESC Ltd", sector: "Power", cap: "Mid Cap" },
  { symbol: "CHALET", name: "Chalet Hotels Ltd", sector: "Hotels", cap: "Mid Cap" },
  { symbol: "CHAMBLFERT", name: "Chambal Fertilisers & Chemicals", sector: "Fertilizers", cap: "Mid Cap" },
  { symbol: "CHEMCON", name: "Chemcon Speciality Chemicals", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "CHEMFAB", name: "Chemfab Alkalis Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "CHENNPETRO", name: "Chennai Petroleum Corp", sector: "Oil & Gas", cap: "Small Cap" },
  { symbol: "CIGNITITEC", name: "Cigniti Technologies Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "CINEVISTA", name: "Cinevista Ltd", sector: "Media", cap: "Small Cap" },
  { symbol: "CLEAN", name: "Clean Science & Technology", sector: "Chemicals", cap: "Mid Cap" },
  { symbol: "CLSEL", name: "Chaman Lal Setia Exports", sector: "FMCG", cap: "Small Cap" },
  { symbol: "COCHINSHIP", name: "Cochin Shipyard Ltd", sector: "Shipbuilding", cap: "Mid Cap" },
  { symbol: "COFFEEDAY", name: "Coffee Day Enterprises", sector: "Retail", cap: "Small Cap" },
  { symbol: "COMPINFO", name: "Compuage Infocom Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "CONFIPET", name: "Confidence Petroleum India", sector: "Oil & Gas", cap: "Small Cap" },
  { symbol: "CONTROLPR", name: "Control Print Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "COSMOFIRST", name: "Cosmo First Ltd", sector: "Packaging", cap: "Small Cap" },
  { symbol: "CRAFTSMAN", name: "Craftsman Automation Ltd", sector: "Auto Ancillary", cap: "Mid Cap" },
  { symbol: "CRISIL", name: "CRISIL Ltd", sector: "Finance", cap: "Mid Cap" },
  { symbol: "CROMPTON", name: "Crompton Greaves Consumer", sector: "Consumer Durables", cap: "Mid Cap" },
  { symbol: "CSBBANK", name: "CSB Bank Ltd", sector: "Banking", cap: "Small Cap" },
  { symbol: "CUB", name: "City Union Bank Ltd", sector: "Banking", cap: "Mid Cap" },
  { symbol: "CUPID", name: "Cupid Ltd", sector: "Healthcare", cap: "Small Cap" },
  
  // D
  { symbol: "DALMIABHA", name: "Dalmia Bharat Ltd", sector: "Cement", cap: "Mid Cap" },
  { symbol: "DALBHARAT", name: "Dalmia Bharat Sugar & Industries", sector: "Sugar", cap: "Small Cap" },
  { symbol: "DATAMATICS", name: "Datamatics Global Services", sector: "IT", cap: "Small Cap" },
  { symbol: "DBCORP", name: "DB Corp Ltd", sector: "Media", cap: "Small Cap" },
  { symbol: "DBL", name: "Dilip Buildcon Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "DBREALTY", name: "D B Realty Ltd", sector: "Real Estate", cap: "Small Cap" },
  { symbol: "DCAL", name: "Dishman Carbogen Amcis", sector: "Pharma", cap: "Small Cap" },
  { symbol: "DCBBANK", name: "DCB Bank Ltd", sector: "Banking", cap: "Small Cap" },
  { symbol: "DCMSHRIRAM", name: "DCM Shriram Ltd", sector: "Diversified", cap: "Mid Cap" },
  { symbol: "DCXINDIA", name: "DCX Systems Ltd", sector: "Defence", cap: "Small Cap" },
  { symbol: "DECCANCE", name: "Deccan Cements Ltd", sector: "Cement", cap: "Small Cap" },
  { symbol: "DEEPAKFERT", name: "Deepak Fertilisers & Petrochemicals", sector: "Fertilizers", cap: "Small Cap" },
  { symbol: "DELTACORP", name: "Delta Corp Ltd", sector: "Gaming", cap: "Small Cap" },
  { symbol: "DENORA", name: "De Nora India Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "DEVYANI", name: "Devyani International Ltd", sector: "QSR", cap: "Mid Cap" },
  { symbol: "DHAMPURSUG", name: "Dhampur Sugar Mills Ltd", sector: "Sugar", cap: "Small Cap" },
  { symbol: "DHANUKA", name: "Dhanuka Agritech Ltd", sector: "Agro Chemicals", cap: "Small Cap" },
  { symbol: "DHARMAJ", name: "Dharmaj Crop Guard Ltd", sector: "Agro Chemicals", cap: "Small Cap" },
  { symbol: "DHANI", name: "Dhani Services Ltd", sector: "Fintech", cap: "Small Cap" },
  { symbol: "DISHTV", name: "Dish TV India Ltd", sector: "Media", cap: "Small Cap" },
  { symbol: "DLINKINDIA", name: "D-Link India Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "DLF", name: "DLF Ltd", sector: "Real Estate", cap: "Large Cap" },
  { symbol: "DOLATALGO", name: "Dolat Algotech Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "DOLLAR", name: "Dollar Industries Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "DONEAR", name: "Donear Industries Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "DPSCLTD", name: "DPS Edutech Ltd", sector: "Education", cap: "Small Cap" },
  { symbol: "DRL", name: "Dwarikesh Sugar Industries", sector: "Sugar", cap: "Small Cap" },
  { symbol: "DRREDDY", name: "Dr Reddy's Laboratories", sector: "Pharma", cap: "Large Cap" },
  { symbol: "DWARKESH", name: "Dwarikesh Sugar Industries", sector: "Sugar", cap: "Small Cap" },
  { symbol: "DYNPRO", name: "Dynemic Products Ltd", sector: "Chemicals", cap: "Small Cap" },
  
  // E
  { symbol: "EASEMYTRIP", name: "Easy Trip Planners Ltd", sector: "Travel", cap: "Small Cap" },
  { symbol: "EDELWEISS", name: "Edelweiss Financial Services", sector: "Finance", cap: "Small Cap" },
  { symbol: "EICHERMOT", name: "Eicher Motors Ltd", sector: "Auto", cap: "Large Cap" },
  { symbol: "EIHOTEL", name: "EIH Ltd", sector: "Hotels", cap: "Mid Cap" },
  { symbol: "ELECTCAST", name: "Electrosteel Castings Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "ELECON", name: "Elecon Engineering Company", sector: "Engineering", cap: "Small Cap" },
  { symbol: "ELGIEQUIP", name: "Elgi Equipments Ltd", sector: "Engineering", cap: "Mid Cap" },
  { symbol: "EMAMILTD", name: "Emami Ltd", sector: "FMCG", cap: "Mid Cap" },
  { symbol: "EMKAY", name: "Emkay Global Financial Services", sector: "Finance", cap: "Small Cap" },
  { symbol: "ENGINERSIN", name: "Engineers India Ltd", sector: "Engineering", cap: "Mid Cap" },
  { symbol: "EPL", name: "EPL Ltd", sector: "Packaging", cap: "Mid Cap" },
  { symbol: "EROSMEDIA", name: "Eros Media World Plc", sector: "Media", cap: "Small Cap" },
  { symbol: "ESABINDIA", name: "ESAB India Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "ESTER", name: "Ester Industries Ltd", sector: "Packaging", cap: "Small Cap" },
  { symbol: "ETHOSLTD", name: "Ethos Ltd", sector: "Retail", cap: "Small Cap" },
  { symbol: "EVERESTIND", name: "Everest Industries Ltd", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "EXCEL", name: "Excel Industries Ltd", sector: "Chemicals", cap: "Small Cap" },
  
  // F
  { symbol: "FACT", name: "Fertilisers And Chemicals Travancore", sector: "Fertilizers", cap: "Small Cap" },
  { symbol: "FCL", name: "Fineotex Chemical Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "FINCABLES", name: "Finolex Cables Ltd", sector: "Cables", cap: "Mid Cap" },
  { symbol: "FINEORG", name: "Fine Organic Industries", sector: "Chemicals", cap: "Mid Cap" },
  { symbol: "FINOPB", name: "Fino Payments Bank Ltd", sector: "Banking", cap: "Small Cap" },
  { symbol: "FINPIPE", name: "Finolex Industries Ltd", sector: "Plastics", cap: "Mid Cap" },
  { symbol: "FIRSTCRY", name: "Brainbees Solutions Ltd", sector: "Retail", cap: "Mid Cap" },
  { symbol: "FIVESTAR", name: "Five-Star Business Finance", sector: "Finance", cap: "Mid Cap" },
  { symbol: "FLUOROCHEM", name: "Gujarat Fluorochemicals Ltd", sector: "Chemicals", cap: "Mid Cap" },
  { symbol: "FMGOETZE", name: "Federal-Mogul Goetze India", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "FORCEMOT", name: "Force Motors Ltd", sector: "Auto", cap: "Mid Cap" },
  { symbol: "FORTIS", name: "Fortis Healthcare Ltd", sector: "Healthcare", cap: "Mid Cap" },
  { symbol: "FOSECOIND", name: "Foseco India Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "FOTAIRO", name: "Foto Air Technologies", sector: "Engineering", cap: "Small Cap" },
  
  // G
  { symbol: "GABRIEL", name: "Gabriel India Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "GALLANTT", name: "Gallantt Ispat Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "GANDHAR", name: "Gandhar Oil Refinery India", sector: "Oil & Gas", cap: "Small Cap" },
  { symbol: "GANESHHOUC", name: "Ganesh Housing Corp Ltd", sector: "Real Estate", cap: "Small Cap" },
  { symbol: "GANECOS", name: "Ganesha Ecosphere Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "GARFIBRES", name: "Garware Technical Fibres", sector: "Textiles", cap: "Mid Cap" },
  { symbol: "GATEWAY", name: "Gateway Distriparks Ltd", sector: "Logistics", cap: "Small Cap" },
  { symbol: "GENESYS", name: "Genesys International Corp", sector: "IT", cap: "Small Cap" },
  { symbol: "GENUSPOWER", name: "Genus Power Infrastructures", sector: "Engineering", cap: "Small Cap" },
  { symbol: "GEOJITFSL", name: "Geojit Financial Services", sector: "Finance", cap: "Small Cap" },
  { symbol: "GESHIP", name: "Great Eastern Shipping Co", sector: "Logistics", cap: "Mid Cap" },
  { symbol: "GET&D", name: "GE T&D India Ltd", sector: "Power", cap: "Small Cap" },
  { symbol: "GFLLIMITED", name: "GFL Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "GHCL", name: "GHCL Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "GICHSGFIN", name: "GIC Housing Finance Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "GILLETTE", name: "Gillette India Ltd", sector: "FMCG", cap: "Mid Cap" },
  { symbol: "GLAND", name: "Gland Pharma Ltd", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "GLAXO", name: "GlaxoSmithKline Pharmaceuticals", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "GLENMARK", name: "Glenmark Pharmaceuticals", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "GLOBALHEALT", name: "Global Health Ltd", sector: "Healthcare", cap: "Mid Cap" },
  { symbol: "GLOBUSSPR", name: "Globus Spirits Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "GMBREW", name: "GM Breweries Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "GMDCLTD", name: "Gujarat Mineral Dev Corp", sector: "Mining", cap: "Small Cap" },
  { symbol: "GMMPFAUDLR", name: "GMM Pfaudler Ltd", sector: "Engineering", cap: "Mid Cap" },
  { symbol: "GMRINFRA", name: "GMR Airports Infrastructure", sector: "Infrastructure", cap: "Mid Cap" },
  { symbol: "GNA", name: "GNA Axles Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "GNFC", name: "Gujarat Narmada Valley Fertilizers", sector: "Fertilizers", cap: "Mid Cap" },
  { symbol: "GOACARBON", name: "Goa Carbon Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "GOCOLORS", name: "Go Fashion India Ltd", sector: "Retail", cap: "Mid Cap" },
  { symbol: "GODREJAGRO", name: "Godrej Agrovet Ltd", sector: "FMCG", cap: "Mid Cap" },
  { symbol: "GODREJIND", name: "Godrej Industries Ltd", sector: "Diversified", cap: "Mid Cap" },
  { symbol: "GOKALDAS", name: "Gokaldas Exports Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "GOKEX", name: "Gokul Refoils And Solvent", sector: "FMCG", cap: "Small Cap" },
  { symbol: "GOLDIAM", name: "Goldiam International Ltd", sector: "Gems & Jewellery", cap: "Small Cap" },
  { symbol: "GOODLUCK", name: "Goodluck India Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "GOODYEAR", name: "Goodyear India Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "GPIL", name: "Godawari Power & Ispat Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "GPPL", name: "Gujarat Pipavav Port Ltd", sector: "Logistics", cap: "Mid Cap" },
  { symbol: "GRAPHITE", name: "Graphite India Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "GRAVITA", name: "Gravita India Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "GREAVESCOT", name: "Greaves Cotton Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "GREENPLY", name: "Greenply Industries Ltd", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "GREENPANEL", name: "Greenpanel Industries Ltd", sector: "Building Materials", cap: "Mid Cap" },
  { symbol: "GRINDWELL", name: "Grindwell Norton Ltd", sector: "Engineering", cap: "Mid Cap" },
  { symbol: "GRMOVER", name: "GRM Overseas Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "GRSE", name: "Garden Reach Shipbuilders", sector: "Shipbuilding", cap: "Mid Cap" },
  { symbol: "GSFC", name: "Gujarat State Fertilizers", sector: "Fertilizers", cap: "Mid Cap" },
  { symbol: "GSPL", name: "Gujarat State Petronet Ltd", sector: "Oil & Gas", cap: "Mid Cap" },
  { symbol: "GTL", name: "GTL Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "GTLINFRA", name: "GTL Infrastructure Ltd", sector: "Telecom", cap: "Small Cap" },
  { symbol: "GUFICBIO", name: "Gufic Biosciences Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "GUJALKALI", name: "Gujarat Alkalies And Chemicals", sector: "Chemicals", cap: "Mid Cap" },
  { symbol: "GUJARATGAS", name: "Gujarat Gas Ltd", sector: "Oil & Gas", cap: "Mid Cap" },
  { symbol: "GUJGASLTD", name: "Gujarat Gas Ltd", sector: "Oil & Gas", cap: "Mid Cap" },
  { symbol: "GULFOILLUB", name: "Gulf Oil Lubricants India", sector: "Oil & Gas", cap: "Small Cap" },
  { symbol: "GULPOLY", name: "Gul Poly Ltd", sector: "Chemicals", cap: "Small Cap" },
  
  // H
  { symbol: "HAL", name: "Hindustan Aeronautics Ltd", sector: "Defence", cap: "Large Cap" },
  { symbol: "HAPPYFORGE", name: "Happy Forgings Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "HARDWYN", name: "Hardwyn India Ltd", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "HARIOMPIPE", name: "Hariom Pipe Industries Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "HARRMALAYA", name: "Harrisons Malayalam Ltd", sector: "Agro", cap: "Small Cap" },
  { symbol: "HATHWAY", name: "Hathway Cable & Datacom", sector: "Media", cap: "Small Cap" },
  { symbol: "HATSUN", name: "Hatsun Agro Product Ltd", sector: "FMCG", cap: "Mid Cap" },
  { symbol: "HAWKINCOOK", name: "Hawkins Cookers Ltd", sector: "Consumer Durables", cap: "Small Cap" },
  { symbol: "HBLPOWER", name: "HBL Power Systems Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "HCC", name: "Hindustan Construction Co", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "HCG", name: "Healthcare Global Enterprises", sector: "Healthcare", cap: "Small Cap" },
  { symbol: "HDFCAMC", name: "HDFC Asset Management Co", sector: "Finance", cap: "Large Cap" },
  { symbol: "HEG", name: "HEG Ltd", sector: "Chemicals", cap: "Mid Cap" },
  { symbol: "HEMIPROP", name: "Hemisphere Properties India", sector: "Real Estate", cap: "Small Cap" },
  { symbol: "HERANBA", name: "Heranba Industries Ltd", sector: "Agro Chemicals", cap: "Small Cap" },
  { symbol: "HERCULES", name: "Hercules Hoists Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "HERITGFOOD", name: "Heritage Foods Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp Ltd", sector: "Auto", cap: "Large Cap" },
  { symbol: "HESTERBIO", name: "Hester Biosciences Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "HGINFRA", name: "H.G. Infra Engineering Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "HGSINFRA", name: "HGS Infra Engineering Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "HIKAL", name: "Hikal Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "HIL", name: "HIL Ltd", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "HILTON", name: "Hilton Metal Forging Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "HIMATSEIDE", name: "Himatsingka Seide Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "HINDCOPPER", name: "Hindustan Copper Ltd", sector: "Metals", cap: "Mid Cap" },
  { symbol: "HINDMOTORS", name: "Hindustan Motors Ltd", sector: "Auto", cap: "Small Cap" },
  { symbol: "HINDNATGLS", name: "Hindusthan National Glass", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "HINDOILEXP", name: "Hindustan Oil Exploration Co", sector: "Oil & Gas", cap: "Small Cap" },
  { symbol: "HINDWAREAP", name: "Hindware Home Innovation", sector: "Building Materials", cap: "Mid Cap" },
  { symbol: "HINDZINC", name: "Hindustan Zinc Ltd", sector: "Metals", cap: "Large Cap" },
  { symbol: "HIRECT", name: "Hind Rectifiers Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "HISARMETAL", name: "Hisar Metal Industries Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "HITECHGEAR", name: "The Hi-Tech Gears Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "HLEGLAS", name: "HLE Glascoat Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "HMVL", name: "Hindustan Media Ventures", sector: "Media", cap: "Small Cap" },
  { symbol: "HOFCL", name: "Home First Finance Company", sector: "Finance", cap: "Small Cap" },
  { symbol: "HOMEFIRST", name: "Home First Finance Company", sector: "Finance", cap: "Mid Cap" },
  { symbol: "HONASA", name: "Honasa Consumer Ltd", sector: "FMCG", cap: "Mid Cap" },
  { symbol: "HONDAPOWER", name: "Honda India Power Products", sector: "Engineering", cap: "Small Cap" },
  { symbol: "HSCL", name: "Himadri Speciality Chemical", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "HSIL", name: "HSIL Ltd", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "HTMEDIA", name: "HT Media Ltd", sector: "Media", cap: "Small Cap" },
  { symbol: "HUDCO", name: "Housing & Urban Dev Corp", sector: "Finance", cap: "Mid Cap" },
  { symbol: "HUHTAMAKI", name: "Huhtamaki India Ltd", sector: "Packaging", cap: "Small Cap" },
  
  // I
  { symbol: "ICEMAKE", name: "Ice Make Refrigeration Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "ICRA", name: "ICRA Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "IDBI", name: "IDBI Bank Ltd", sector: "Banking", cap: "Mid Cap" },
  { symbol: "IEX", name: "Indian Energy Exchange Ltd", sector: "Power", cap: "Mid Cap" },
  { symbol: "IFBIND", name: "IFB Industries Ltd", sector: "Consumer Durables", cap: "Small Cap" },
  { symbol: "IGARASHI", name: "Igarashi Motors India Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "IGPL", name: "IG Petrochemicals Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "IGL", name: "Indraprastha Gas Ltd", sector: "Oil & Gas", cap: "Mid Cap" },
  { symbol: "IIFLSEC", name: "IIFL Securities Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "IIFLWAM", name: "IIFL Wealth Management", sector: "Finance", cap: "Small Cap" },
  { symbol: "IMFA", name: "Indian Metals & Ferro Alloys", sector: "Metals", cap: "Small Cap" },
  { symbol: "INDHOTEL", name: "The Indian Hotels Co Ltd", sector: "Hotels", cap: "Mid Cap" },
  { symbol: "INDIACEM", name: "The India Cements Ltd", sector: "Cement", cap: "Small Cap" },
  { symbol: "INDIAGLYCO", name: "India Glycols Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "INDIANB", name: "Indian Bank", sector: "Banking", cap: "Mid Cap" },
  { symbol: "INDIANHUME", name: "Indian Hume Pipe Co Ltd", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "INDIGO", name: "InterGlobe Aviation Ltd", sector: "Aviation", cap: "Large Cap" },
  { symbol: "INDNIPPON", name: "India Nippon Electricals", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "INDOCO", name: "Indoco Remedies Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "INDORAMA", name: "Indo Rama Synthetics India", sector: "Textiles", cap: "Small Cap" },
  { symbol: "INDOSTAR", name: "IndoStar Capital Finance", sector: "Finance", cap: "Small Cap" },
  { symbol: "INDOTECH", name: "Indo Tech Transformers", sector: "Engineering", cap: "Small Cap" },
  { symbol: "INDRAMEDCO", name: "Indraprastha Medical Corp", sector: "Healthcare", cap: "Small Cap" },
  { symbol: "INDSWFTLAB", name: "Ind-Swift Laboratories Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "INFIBEAM", name: "Infibeam Avenues Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "INGERRAND", name: "Ingersoll-Rand India Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "INOXGREEN", name: "Inox Green Energy Services", sector: "Power", cap: "Small Cap" },
  { symbol: "INOXWIND", name: "Inox Wind Ltd", sector: "Power", cap: "Small Cap" },
  { symbol: "INSECTICID", name: "Insecticides India Ltd", sector: "Agro Chemicals", cap: "Small Cap" },
  { symbol: "INTELLECT", name: "Intellect Design Arena", sector: "IT", cap: "Mid Cap" },
  { symbol: "IOB", name: "Indian Overseas Bank", sector: "Banking", cap: "Mid Cap" },
  { symbol: "IPCALAB", name: "IPCA Laboratories Ltd", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "IRB", name: "IRB Infrastructure Developers", sector: "Infrastructure", cap: "Mid Cap" },
  { symbol: "IRCON", name: "Ircon International Ltd", sector: "Infrastructure", cap: "Mid Cap" },
  { symbol: "IRCTC", name: "Indian Railway Catering", sector: "Travel", cap: "Mid Cap" },
  { symbol: "IREDA", name: "Indian Renewable Energy Dev Agency", sector: "Finance", cap: "Mid Cap" },
  { symbol: "ISEC", name: "ICICI Securities Ltd", sector: "Finance", cap: "Mid Cap" },
  { symbol: "ISFT", name: "Intrasoft Technologies Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "ITDC", name: "India Tourism Dev Corp", sector: "Hotels", cap: "Small Cap" },
  { symbol: "ITI", name: "ITI Ltd", sector: "Telecom", cap: "Small Cap" },
  { symbol: "ITURIN", name: "Iturin India Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "IVP", name: "IVP Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "IZMO", name: "IZMO Ltd", sector: "IT", cap: "Small Cap" },
];

// Even more stocks - J to Z
export const MORE_NSE_STOCKS_2: StockSeed[] = [
  // J
  { symbol: "J&KBANK", name: "Jammu & Kashmir Bank", sector: "Banking", cap: "Small Cap" },
  { symbol: "JAGRAN", name: "Jagran Prakashan Ltd", sector: "Media", cap: "Small Cap" },
  { symbol: "JAIBALAJI", name: "Jai Balaji Industries Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "JAICORPLTD", name: "Jai Corp Ltd", sector: "Diversified", cap: "Small Cap" },
  { symbol: "JAMNAAUTO", name: "Jamna Auto Industries", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "JASH", name: "Jash Engineering Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "JAYNECOIND", name: "Jayaswal Neco Industries", sector: "Metals", cap: "Small Cap" },
  { symbol: "JBCHEPHARM", name: "JB Chemicals & Pharmaceuticals", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "JBMA", name: "JBM Auto Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "JETAIRWAYS", name: "Jet Airways India Ltd", sector: "Aviation", cap: "Small Cap" },
  { symbol: "JHS", name: "JHS Svendgaard Laboratories", sector: "FMCG", cap: "Small Cap" },
  { symbol: "JINDALPOLY", name: "Jindal Poly Films Ltd", sector: "Packaging", cap: "Small Cap" },
  { symbol: "JINDALSAW", name: "Jindal Saw Ltd", sector: "Metals", cap: "Mid Cap" },
  { symbol: "JISLJALEQS", name: "Jain Irrigation Systems", sector: "Agro", cap: "Small Cap" },
  { symbol: "JKIL", name: "J. Kumar Infraprojects Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "JKLAKSHMI", name: "JK Lakshmi Cement Ltd", sector: "Cement", cap: "Mid Cap" },
  { symbol: "JKPAPER", name: "JK Paper Ltd", sector: "Paper", cap: "Mid Cap" },
  { symbol: "JKTYRE", name: "JK Tyre & Industries Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "JMCPROJECT", name: "JMC Projects India Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "JMFINANCIL", name: "JM Financial Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "JOCIL", name: "Jocil Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "JPASSOCIAT", name: "Jaiprakash Associates Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "JPOLYINVST", name: "Jindal Poly Investment & Finance", sector: "Finance", cap: "Small Cap" },
  { symbol: "JPPOWER", name: "Jaiprakash Power Ventures", sector: "Power", cap: "Small Cap" },
  { symbol: "JSL", name: "Jindal Stainless Ltd", sector: "Metals", cap: "Mid Cap" },
  { symbol: "JSLHISAR", name: "Jindal Stainless Hisar", sector: "Metals", cap: "Mid Cap" },
  { symbol: "JSWENERGY", name: "JSW Energy Ltd", sector: "Power", cap: "Mid Cap" },
  { symbol: "JSWHL", name: "JSW Holdings Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "JSWISPL", name: "JSW Infrastructure Ltd", sector: "Infrastructure", cap: "Mid Cap" },
  { symbol: "JTEKTINDIA", name: "JTEKT India Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "JUBLINDS", name: "Jubilant Industries Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "JUNIPER", name: "Juniper Hotels Ltd", sector: "Hotels", cap: "Small Cap" },
  { symbol: "JUSTDIAL", name: "Just Dial Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "JYOTHYLAB", name: "Jyothy Labs Ltd", sector: "FMCG", cap: "Mid Cap" },
  
  // K
  { symbol: "KAJARIACER", name: "Kajaria Ceramics Ltd", sector: "Building Materials", cap: "Mid Cap" },
  { symbol: "KALYANKJIL", name: "Kalyan Jewellers India", sector: "Gems & Jewellery", cap: "Mid Cap" },
  { symbol: "KAMAHOLD", name: "Kamat Hotels India Ltd", sector: "Hotels", cap: "Small Cap" },
  { symbol: "KAMDHENU", name: "Kamdhenu Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "KANCHI", name: "Kanchi Karpooram Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "KANORICHEM", name: "Kanoria Chemicals & Industries", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "KANSAINER", name: "Kansai Nerolac Paints", sector: "Paints", cap: "Mid Cap" },
  { symbol: "KAPSTON", name: "Kapston Facilities Management", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "KARMAENG", name: "Karma Energy Ltd", sector: "Power", cap: "Small Cap" },
  { symbol: "KARURVYSYA", name: "Karur Vysya Bank", sector: "Banking", cap: "Small Cap" },
  { symbol: "KAYNES", name: "Kaynes Technology India", sector: "Electronics", cap: "Mid Cap" },
  { symbol: "KDDL", name: "KDDL Ltd", sector: "Consumer Goods", cap: "Small Cap" },
  { symbol: "KEC", name: "KEC International Ltd", sector: "Infrastructure", cap: "Mid Cap" },
  { symbol: "KEI", name: "KEI Industries Ltd", sector: "Cables", cap: "Mid Cap" },
  { symbol: "KELLTONTEC", name: "Kellton Tech Solutions", sector: "IT", cap: "Small Cap" },
  { symbol: "KESORAMIND", name: "Kesoram Industries Ltd", sector: "Cement", cap: "Small Cap" },
  { symbol: "KINGFA", name: "Kingfa Science & Technology", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "KIRIINDUS", name: "Kiri Industries Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "KIRLOSENG", name: "Kirloskar Oil Engines Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "KIRLOSIND", name: "Kirloskar Industries Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "KITEX", name: "Kitex Garments Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "KMCSHIL", name: "KMC Speciality Hospitals", sector: "Healthcare", cap: "Small Cap" },
  { symbol: "KMSUGAR", name: "KM Sugar Mills Ltd", sector: "Sugar", cap: "Small Cap" },
  { symbol: "KNRCON", name: "KNR Constructions Ltd", sector: "Infrastructure", cap: "Mid Cap" },
  { symbol: "KOLTEPATIL", name: "Kolte-Patil Developers", sector: "Real Estate", cap: "Small Cap" },
  { symbol: "KOPRAN", name: "Kopran Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank Ltd", sector: "Banking", cap: "Large Cap" },
  { symbol: "KPIGREEN", name: "KP Energy Ltd", sector: "Power", cap: "Small Cap" },
  { symbol: "KPIL", name: "Kalpataru Projects International", sector: "Infrastructure", cap: "Mid Cap" },
  { symbol: "KPITTECH", name: "KPIT Technologies Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "KRBL", name: "KRBL Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "KSCL", name: "Kaveri Seed Company Ltd", sector: "Agro", cap: "Mid Cap" },
  { symbol: "KSOLVES", name: "Ksolves India Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "KUANTUM", name: "Kuantum Papers Ltd", sector: "Paper", cap: "Small Cap" },
  { symbol: "L&TFH", name: "L&T Finance Holdings", sector: "Finance", cap: "Mid Cap" },
  
  // L
  { symbol: "LAOPALA", name: "La Opala RG Ltd", sector: "Consumer Goods", cap: "Small Cap" },
  { symbol: "LASA", name: "Lasa Supergenerics Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "LATENTVIEW", name: "Latent View Analytics Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "LAURUSLABS", name: "Laurus Labs Ltd", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "LAXMIMACH", name: "Lakshmi Machine Works", sector: "Engineering", cap: "Mid Cap" },
  { symbol: "LEMONTREE", name: "Lemon Tree Hotels Ltd", sector: "Hotels", cap: "Small Cap" },
  { symbol: "LGBBROSLTD", name: "LG Balakrishnan & Bros", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "LICHSGFIN", name: "LIC Housing Finance Ltd", sector: "Finance", cap: "Mid Cap" },
  { symbol: "LINCOLN", name: "Lincoln Pharmaceuticals", sector: "Pharma", cap: "Small Cap" },
  { symbol: "LINDEINDIA", name: "Linde India Ltd", sector: "Chemicals", cap: "Mid Cap" },
  { symbol: "LIKHITHA", name: "Likhitha Infrastructure", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "LLOYDSENGG", name: "Lloyds Engineering Works", sector: "Engineering", cap: "Small Cap" },
  { symbol: "LLOYDSME", name: "Lloyds Metals And Energy", sector: "Metals", cap: "Mid Cap" },
  { symbol: "LODHA", name: "Macrotech Developers Ltd", sector: "Real Estate", cap: "Mid Cap" },
  { symbol: "LOKESHMACH", name: "Lokesh Machines Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "LSIL", name: "Laxmi Surgical Industries", sector: "Healthcare", cap: "Small Cap" },
  { symbol: "LTIM", name: "LTIMindtree Ltd", sector: "IT", cap: "Large Cap" },
  { symbol: "LTTS", name: "L&T Technology Services", sector: "IT", cap: "Mid Cap" },
  { symbol: "LUPIN", name: "Lupin Ltd", sector: "Pharma", cap: "Large Cap" },
  { symbol: "LUXIND", name: "Lux Industries Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "LXCHEM", name: "Laxmi Organic Industries", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "LYKALABS", name: "Lyka Labs Ltd", sector: "Pharma", cap: "Small Cap" },
  
  // M
  { symbol: "M&M", name: "Mahindra & Mahindra Ltd", sector: "Auto", cap: "Large Cap" },
  { symbol: "M&MFIN", name: "Mahindra & Mahindra Financial Services", sector: "Finance", cap: "Mid Cap" },
  { symbol: "MAANALU", name: "Maan Aluminium Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "MACPOWER", name: "Macpower CNC Machines", sector: "Engineering", cap: "Small Cap" },
  { symbol: "MADHAV", name: "Madhav Marbles & Granites", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "MAHABANK", name: "Bank of Maharashtra", sector: "Banking", cap: "Mid Cap" },
  { symbol: "MAHAPEXLTD", name: "Maha Rashtra Apex Corp", sector: "Diversified", cap: "Small Cap" },
  { symbol: "MAHINDCIE", name: "Mahindra CIE Automotive", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "MAHLIFE", name: "Mahindra Lifespace Developers", sector: "Real Estate", cap: "Mid Cap" },
  { symbol: "MAHLOG", name: "Mahindra Logistics Ltd", sector: "Logistics", cap: "Small Cap" },
  { symbol: "MAHSCOOTER", name: "Maharashtra Scooters Ltd", sector: "Auto", cap: "Small Cap" },
  { symbol: "MAHSEAMLES", name: "Maharashtra Seamless Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "MAITHANALL", name: "Maithan Alloys Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "MALLCOM", name: "Mallcom India Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "MANALIPETC", name: "Manali Petrochemicals", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "MANAPPURAM", name: "Manappuram Finance Ltd", sector: "Finance", cap: "Mid Cap" },
  { symbol: "MANGALAM", name: "Mangalam Drugs & Organics", sector: "Pharma", cap: "Small Cap" },
  { symbol: "MANGLMCEM", name: "Mangalam Cement Ltd", sector: "Cement", cap: "Small Cap" },
  { symbol: "MANINDS", name: "Man Industries India Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "MANINFRA", name: "Man Infraconstruction Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "MANKIND", name: "Mankind Pharma Ltd", sector: "Pharma", cap: "Large Cap" },
  { symbol: "MAPMYINDIA", name: "CE Info Systems Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "MARKSANS", name: "Marksans Pharma Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "MASTEK", name: "Mastek Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "MATRIMONY", name: "Matrimony.com Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "MAWANASUG", name: "Mawana Sugars Ltd", sector: "Sugar", cap: "Small Cap" },
  { symbol: "MAXHEALTH", name: "Max Healthcare Institute", sector: "Healthcare", cap: "Mid Cap" },
  { symbol: "MAXINDIA", name: "Max India Ltd", sector: "Healthcare", cap: "Small Cap" },
  { symbol: "MAYURUNIQ", name: "Mayur Uniquoters Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "MAZDOCK", name: "Mazagon Dock Shipbuilders", sector: "Shipbuilding", cap: "Mid Cap" },
  { symbol: "MBAPL", name: "Madhya Bharat Agro Products", sector: "Agro", cap: "Small Cap" },
  { symbol: "MBLINFRA", name: "MBL Infrastructures Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "MCDOWELL-N", name: "United Spirits Ltd", sector: "FMCG", cap: "Large Cap" },
  { symbol: "MCX", name: "Multi Commodity Exchange", sector: "Finance", cap: "Mid Cap" },
  { symbol: "MEDPLUS", name: "MedPlus Health Services", sector: "Healthcare", cap: "Mid Cap" },
  { symbol: "MEGASOFT", name: "Megasoft Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "MEGH", name: "Meghmani Organics Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "MELSTAR", name: "Melstar Information Tech", sector: "IT", cap: "Small Cap" },
  { symbol: "MEP", name: "MEP Infrastructure Developers", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "METROBRAND", name: "Metro Brands Ltd", sector: "Footwear", cap: "Mid Cap" },
  { symbol: "METROPOLIS", name: "Metropolis Healthcare", sector: "Healthcare", cap: "Mid Cap" },
  { symbol: "MFSL", name: "Max Financial Services", sector: "Insurance", cap: "Mid Cap" },
  { symbol: "MGL", name: "Mahanagar Gas Ltd", sector: "Oil & Gas", cap: "Mid Cap" },
  { symbol: "MHRIL", name: "Mahindra Holidays & Resorts", sector: "Hotels", cap: "Mid Cap" },
  { symbol: "MIDHANI", name: "Mishra Dhatu Nigam Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "MINDACORP", name: "Minda Corporation Ltd", sector: "Auto Ancillary", cap: "Mid Cap" },
  { symbol: "MINDTREE", name: "MindTree Ltd", sector: "IT", cap: "Large Cap" },
  { symbol: "MMFL", name: "MM Forgings Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "MMTC", name: "MMTC Ltd", sector: "Trading", cap: "Small Cap" },
  { symbol: "MOL", name: "Meghmani Organics Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "MOLDTECH", name: "Mold-Tek Technologies Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "MOLDTKPAC", name: "Mold-Tek Packaging Ltd", sector: "Packaging", cap: "Small Cap" },
  { symbol: "MONTECARLO", name: "Monte Carlo Fashions Ltd", sector: "Retail", cap: "Small Cap" },
  { symbol: "MORARJEE", name: "Morarjee Textiles Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "MOREPENLAB", name: "Morepen Laboratories Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "MOTILALOFS", name: "Motilal Oswal Financial Services", sector: "Finance", cap: "Mid Cap" },
  { symbol: "MPSLTD", name: "MPS Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "MRPL", name: "Mangalore Refinery & Petrochemicals", sector: "Oil & Gas", cap: "Mid Cap" },
  { symbol: "MSTCLTD", name: "MSTC Ltd", sector: "Trading", cap: "Small Cap" },
  { symbol: "MTARTECH", name: "MTAR Technologies Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "MTEDUCARE", name: "MT Educare Ltd", sector: "Education", cap: "Small Cap" },
  { symbol: "MTNL", name: "Mahanagar Telephone Nigam", sector: "Telecom", cap: "Small Cap" },
  { symbol: "MUKANDLTD", name: "Mukand Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "MUNJALAU", name: "Munjal Auto Industries", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "MUNJALSHOW", name: "Munjal Showa Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "MURUDCERA", name: "Murudeshwar Ceramics Ltd", sector: "Building Materials", cap: "Small Cap" },
];

export default [...MORE_NSE_STOCKS, ...MORE_NSE_STOCKS_2];
