// Comprehensive list of NSE + BSE stocks for Indian market
// This file contains ~2000+ stocks with their details

export interface StockSeed {
  symbol: string;
  name: string;
  sector: string;
  cap: "Large Cap" | "Mid Cap" | "Small Cap";
}

// Sector classification based on industry
const SECTOR_KEYWORDS: Record<string, string[]> = {
  "Banking": ["Bank", "Banking"],
  "IT": ["Software", "Tech", "Infotech", "IT", "Computer", "Digital", "Cyber", "Systems"],
  "Pharma": ["Pharma", "Healthcare", "Medicine", "Drug", "Bio", "Laboratories", "Lab"],
  "FMCG": ["Consumer", "Foods", "Beverages", "Personal", "FMCG"],
  "Auto": ["Auto", "Motor", "Vehicle", "Car", "Tyre", "Maruti", "Mahindra"],
  "Finance": ["Finance", "Financial", "Credit", "Loan", "Investment", "Capital", "Insurance"],
  "Infrastructure": ["Infra", "Construction", "Engineering", "Cement", "Real Estate", "Realty"],
  "Oil & Gas": ["Oil", "Gas", "Petroleum", "Petro", "Refinery", "Energy"],
  "Metals": ["Steel", "Metal", "Iron", "Alumin", "Copper", "Zinc", "Mining"],
  "Power": ["Power", "Electric", "Energy"],
  "Telecom": ["Telecom", "Communication", "Airtel", "Vodafone"],
  "Chemicals": ["Chemical", "Fertilizer", "Agro"],
  "Textiles": ["Textile", "Cotton", "Yarn", "Fabric", "Garment", "Apparel"],
  "Retail": ["Retail", "Store", "Mart", "Shop"],
  "Hotels": ["Hotel", "Hospitality", "Resort", "Tourism", "Travel"],
  "Media": ["Media", "Entertainment", "Film", "TV", "Broadcast"],
  "Logistics": ["Logistics", "Transport", "Shipping", "Cargo", "Container"],
};

export function inferSector(companyName: string): string {
  const name = companyName.toLowerCase();
  for (const [sector, keywords] of Object.entries(SECTOR_KEYWORDS)) {
    if (keywords.some(kw => name.includes(kw.toLowerCase()))) {
      return sector;
    }
  }
  return "Others";
}

// Large cap stocks (Nifty 50 + Nifty Next 50)
export const LARGE_CAP_STOCKS: StockSeed[] = [
  // Nifty 50 Stocks
  { symbol: "RELIANCE", name: "Reliance Industries Ltd", sector: "Oil & Gas", cap: "Large Cap" },
  { symbol: "TCS", name: "Tata Consultancy Services Ltd", sector: "IT", cap: "Large Cap" },
  { symbol: "HDFCBANK", name: "HDFC Bank Ltd", sector: "Banking", cap: "Large Cap" },
  { symbol: "INFY", name: "Infosys Ltd", sector: "IT", cap: "Large Cap" },
  { symbol: "ICICIBANK", name: "ICICI Bank Ltd", sector: "Banking", cap: "Large Cap" },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever Ltd", sector: "FMCG", cap: "Large Cap" },
  { symbol: "ITC", name: "ITC Ltd", sector: "FMCG", cap: "Large Cap" },
  { symbol: "SBIN", name: "State Bank of India", sector: "Banking", cap: "Large Cap" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel Ltd", sector: "Telecom", cap: "Large Cap" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank Ltd", sector: "Banking", cap: "Large Cap" },
  { symbol: "BAJFINANCE", name: "Bajaj Finance Ltd", sector: "Finance", cap: "Large Cap" },
  { symbol: "LICI", name: "Life Insurance Corporation", sector: "Insurance", cap: "Large Cap" },
  { symbol: "LT", name: "Larsen & Toubro Ltd", sector: "Infrastructure", cap: "Large Cap" },
  { symbol: "HCLTECH", name: "HCL Technologies Ltd", sector: "IT", cap: "Large Cap" },
  { symbol: "ASIANPAINT", name: "Asian Paints Ltd", sector: "Paints", cap: "Large Cap" },
  { symbol: "AXISBANK", name: "Axis Bank Ltd", sector: "Banking", cap: "Large Cap" },
  { symbol: "MARUTI", name: "Maruti Suzuki India Ltd", sector: "Auto", cap: "Large Cap" },
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical Industries", sector: "Pharma", cap: "Large Cap" },
  { symbol: "TITAN", name: "Titan Company Ltd", sector: "Consumer Goods", cap: "Large Cap" },
  { symbol: "DMART", name: "Avenue Supermarts Ltd", sector: "Retail", cap: "Large Cap" },
  { symbol: "TATAMOTORS", name: "Tata Motors Ltd", sector: "Auto", cap: "Large Cap" },
  { symbol: "NTPC", name: "NTPC Ltd", sector: "Power", cap: "Large Cap" },
  { symbol: "POWERGRID", name: "Power Grid Corporation", sector: "Power", cap: "Large Cap" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement Ltd", sector: "Cement", cap: "Large Cap" },
  { symbol: "WIPRO", name: "Wipro Ltd", sector: "IT", cap: "Large Cap" },
  { symbol: "ONGC", name: "Oil & Natural Gas Corporation", sector: "Oil & Gas", cap: "Large Cap" },
  { symbol: "JSWSTEEL", name: "JSW Steel Ltd", sector: "Metals", cap: "Large Cap" },
  { symbol: "TATASTEEL", name: "Tata Steel Ltd", sector: "Metals", cap: "Large Cap" },
  { symbol: "M&M", name: "Mahindra & Mahindra Ltd", sector: "Auto", cap: "Large Cap" },
  { symbol: "ADANIENT", name: "Adani Enterprises Ltd", sector: "Infrastructure", cap: "Large Cap" },
  { symbol: "ADANIPORTS", name: "Adani Ports & SEZ Ltd", sector: "Infrastructure", cap: "Large Cap" },
  { symbol: "COALINDIA", name: "Coal India Ltd", sector: "Mining", cap: "Large Cap" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv Ltd", sector: "Finance", cap: "Large Cap" },
  { symbol: "TECHM", name: "Tech Mahindra Ltd", sector: "IT", cap: "Large Cap" },
  { symbol: "NESTLEIND", name: "Nestle India Ltd", sector: "FMCG", cap: "Large Cap" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank Ltd", sector: "Banking", cap: "Large Cap" },
  { symbol: "BPCL", name: "Bharat Petroleum Corporation", sector: "Oil & Gas", cap: "Large Cap" },
  { symbol: "HINDALCO", name: "Hindalco Industries Ltd", sector: "Metals", cap: "Large Cap" },
  { symbol: "DIVISLAB", name: "Divi's Laboratories Ltd", sector: "Pharma", cap: "Large Cap" },
  { symbol: "GRASIM", name: "Grasim Industries Ltd", sector: "Cement", cap: "Large Cap" },
  { symbol: "DRREDDY", name: "Dr Reddy's Laboratories", sector: "Pharma", cap: "Large Cap" },
  { symbol: "CIPLA", name: "Cipla Ltd", sector: "Pharma", cap: "Large Cap" },
  { symbol: "EICHERMOT", name: "Eicher Motors Ltd", sector: "Auto", cap: "Large Cap" },
  { symbol: "BRITANNIA", name: "Britannia Industries Ltd", sector: "FMCG", cap: "Large Cap" },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals Enterprise", sector: "Healthcare", cap: "Large Cap" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp Ltd", sector: "Auto", cap: "Large Cap" },
  { symbol: "TATACONSUM", name: "Tata Consumer Products Ltd", sector: "FMCG", cap: "Large Cap" },
  { symbol: "SBILIFE", name: "SBI Life Insurance Company", sector: "Insurance", cap: "Large Cap" },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto Ltd", sector: "Auto", cap: "Large Cap" },
  { symbol: "HDFCLIFE", name: "HDFC Life Insurance Company", sector: "Insurance", cap: "Large Cap" },
  // Nifty Next 50
  { symbol: "ADANIGREEN", name: "Adani Green Energy Ltd", sector: "Power", cap: "Large Cap" },
  { symbol: "VEDL", name: "Vedanta Ltd", sector: "Mining", cap: "Large Cap" },
  { symbol: "DLF", name: "DLF Ltd", sector: "Real Estate", cap: "Large Cap" },
  { symbol: "GODREJCP", name: "Godrej Consumer Products", sector: "FMCG", cap: "Large Cap" },
  { symbol: "HAVELLS", name: "Havells India Ltd", sector: "Consumer Durables", cap: "Large Cap" },
  { symbol: "SIEMENS", name: "Siemens Ltd", sector: "Engineering", cap: "Large Cap" },
  { symbol: "AMBUJACEM", name: "Ambuja Cements Ltd", sector: "Cement", cap: "Large Cap" },
  { symbol: "DABUR", name: "Dabur India Ltd", sector: "FMCG", cap: "Large Cap" },
  { symbol: "IOC", name: "Indian Oil Corporation Ltd", sector: "Oil & Gas", cap: "Large Cap" },
  { symbol: "BANKBARODA", name: "Bank of Baroda", sector: "Banking", cap: "Large Cap" },
  { symbol: "PNB", name: "Punjab National Bank", sector: "Banking", cap: "Large Cap" },
  { symbol: "PIDILITIND", name: "Pidilite Industries Ltd", sector: "Chemicals", cap: "Large Cap" },
  { symbol: "ICICIPRULI", name: "ICICI Prudential Life Insurance", sector: "Insurance", cap: "Large Cap" },
  { symbol: "ICICIGI", name: "ICICI Lombard General Insurance", sector: "Insurance", cap: "Large Cap" },
  { symbol: "INDIGO", name: "InterGlobe Aviation Ltd", sector: "Aviation", cap: "Large Cap" },
  { symbol: "SHREECEM", name: "Shree Cement Ltd", sector: "Cement", cap: "Large Cap" },
  { symbol: "MARICO", name: "Marico Ltd", sector: "FMCG", cap: "Large Cap" },
  { symbol: "BERGEPAINT", name: "Berger Paints India Ltd", sector: "Paints", cap: "Large Cap" },
  { symbol: "CHOLAFIN", name: "Cholamandalam Investment & Finance", sector: "Finance", cap: "Large Cap" },
  { symbol: "BIOCON", name: "Biocon Ltd", sector: "Pharma", cap: "Large Cap" },
  { symbol: "BOSCHLTD", name: "Bosch Ltd", sector: "Auto Ancillary", cap: "Large Cap" },
  { symbol: "NAUKRI", name: "Info Edge India Ltd", sector: "IT", cap: "Large Cap" },
  { symbol: "COLPAL", name: "Colgate-Palmolive India Ltd", sector: "FMCG", cap: "Large Cap" },
  { symbol: "TORNTPHARM", name: "Torrent Pharmaceuticals Ltd", sector: "Pharma", cap: "Large Cap" },
  { symbol: "MCDOWELL-N", name: "United Spirits Ltd", sector: "FMCG", cap: "Large Cap" },
  { symbol: "GAIL", name: "GAIL India Ltd", sector: "Oil & Gas", cap: "Large Cap" },
  { symbol: "HINDPETRO", name: "Hindustan Petroleum Corporation", sector: "Oil & Gas", cap: "Large Cap" },
  { symbol: "TATAPOWER", name: "Tata Power Company Ltd", sector: "Power", cap: "Large Cap" },
  { symbol: "JINDALSTEL", name: "Jindal Steel & Power Ltd", sector: "Metals", cap: "Large Cap" },
  { symbol: "ZOMATO", name: "Zomato Ltd", sector: "Internet", cap: "Large Cap" },
];

// Mid cap stocks (Nifty Midcap 150)
export const MID_CAP_STOCKS: StockSeed[] = [
  { symbol: "MUTHOOTFIN", name: "Muthoot Finance Ltd", sector: "Finance", cap: "Mid Cap" },
  { symbol: "VOLTAS", name: "Voltas Ltd", sector: "Consumer Durables", cap: "Mid Cap" },
  { symbol: "AUROPHARMA", name: "Aurobindo Pharma Ltd", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "TATAELXSI", name: "Tata Elxsi Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "PERSISTENT", name: "Persistent Systems Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "COFORGE", name: "Coforge Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "POLYCAB", name: "Polycab India Ltd", sector: "Cables", cap: "Mid Cap" },
  { symbol: "TRENT", name: "Trent Ltd", sector: "Retail", cap: "Mid Cap" },
  { symbol: "MPHASIS", name: "MphasiS Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "FEDERALBNK", name: "Federal Bank Ltd", sector: "Banking", cap: "Mid Cap" },
  { symbol: "INDHOTEL", name: "Indian Hotels Co Ltd", sector: "Hotels", cap: "Mid Cap" },
  { symbol: "PAGEIND", name: "Page Industries Ltd", sector: "Textiles", cap: "Mid Cap" },
  { symbol: "ASTRAL", name: "Astral Ltd", sector: "Plastics", cap: "Mid Cap" },
  { symbol: "CUMMINSIND", name: "Cummins India Ltd", sector: "Engineering", cap: "Mid Cap" },
  { symbol: "ESCORTS", name: "Escorts Kubota Ltd", sector: "Auto", cap: "Mid Cap" },
  { symbol: "OBEROIRLTY", name: "Oberoi Realty Ltd", sector: "Real Estate", cap: "Mid Cap" },
  { symbol: "LTTS", name: "L&T Technology Services", sector: "IT", cap: "Mid Cap" },
  { symbol: "LALPATHLAB", name: "Dr Lal PathLabs Ltd", sector: "Healthcare", cap: "Mid Cap" },
  { symbol: "ASHOKLEY", name: "Ashok Leyland Ltd", sector: "Auto", cap: "Mid Cap" },
  { symbol: "CROMPTON", name: "Crompton Greaves Consumer", sector: "Consumer Durables", cap: "Mid Cap" },
  { symbol: "ACC", name: "ACC Ltd", sector: "Cement", cap: "Mid Cap" },
  { symbol: "ATUL", name: "Atul Ltd", sector: "Chemicals", cap: "Mid Cap" },
  { symbol: "SYNGENE", name: "Syngene International Ltd", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "COROMANDEL", name: "Coromandel International Ltd", sector: "Fertilizers", cap: "Mid Cap" },
  { symbol: "CONCOR", name: "Container Corporation of India", sector: "Logistics", cap: "Mid Cap" },
  { symbol: "DIXON", name: "Dixon Technologies India Ltd", sector: "Consumer Electronics", cap: "Mid Cap" },
  { symbol: "AUBANK", name: "AU Small Finance Bank Ltd", sector: "Banking", cap: "Mid Cap" },
  { symbol: "NMDC", name: "NMDC Ltd", sector: "Mining", cap: "Mid Cap" },
  { symbol: "ALKEM", name: "Alkem Laboratories Ltd", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "IDFCFIRSTB", name: "IDFC First Bank Ltd", sector: "Banking", cap: "Mid Cap" },
  { symbol: "BALKRISIND", name: "Balkrishna Industries Ltd", sector: "Auto Ancillary", cap: "Mid Cap" },
  { symbol: "TATACOMM", name: "Tata Communications Ltd", sector: "Telecom", cap: "Mid Cap" },
  { symbol: "SAIL", name: "Steel Authority of India Ltd", sector: "Metals", cap: "Mid Cap" },
  { symbol: "PETRONET", name: "Petronet LNG Ltd", sector: "Oil & Gas", cap: "Mid Cap" },
  { symbol: "LUPIN", name: "Lupin Ltd", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "BHARATFORG", name: "Bharat Forge Ltd", sector: "Auto Ancillary", cap: "Mid Cap" },
  { symbol: "SRIRAMFIN", name: "Shriram Finance Ltd", sector: "Finance", cap: "Mid Cap" },
  { symbol: "UNIONBANK", name: "Union Bank of India", sector: "Banking", cap: "Mid Cap" },
  { symbol: "BANDHANBNK", name: "Bandhan Bank Ltd", sector: "Banking", cap: "Mid Cap" },
  { symbol: "CANBK", name: "Canara Bank", sector: "Banking", cap: "Mid Cap" },
  { symbol: "INDUSTOWER", name: "Indus Towers Ltd", sector: "Telecom", cap: "Mid Cap" },
  { symbol: "MOTHERSON", name: "Samvardhana Motherson International", sector: "Auto Ancillary", cap: "Mid Cap" },
  { symbol: "JUBLFOOD", name: "Jubilant Foodworks Ltd", sector: "QSR", cap: "Mid Cap" },
  { symbol: "PGHH", name: "Procter & Gamble Hygiene", sector: "FMCG", cap: "Mid Cap" },
  { symbol: "MAXHEALTH", name: "Max Healthcare Institute", sector: "Healthcare", cap: "Mid Cap" },
  { symbol: "RECLTD", name: "REC Ltd", sector: "Finance", cap: "Mid Cap" },
  { symbol: "PFC", name: "Power Finance Corporation Ltd", sector: "Finance", cap: "Mid Cap" },
  { symbol: "NIACL", name: "New India Assurance Co Ltd", sector: "Insurance", cap: "Mid Cap" },
  { symbol: "GICRE", name: "General Insurance Corporation", sector: "Insurance", cap: "Mid Cap" },
  { symbol: "SUNDARMFIN", name: "Sundaram Finance Ltd", sector: "Finance", cap: "Mid Cap" },
  { symbol: "PRESTIGE", name: "Prestige Estates Projects", sector: "Real Estate", cap: "Mid Cap" },
  { symbol: "PHOENIXLTD", name: "Phoenix Mills Ltd", sector: "Real Estate", cap: "Mid Cap" },
  { symbol: "ZYDUSLIFE", name: "Zydus Lifesciences Ltd", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "METROPOLIS", name: "Metropolis Healthcare Ltd", sector: "Healthcare", cap: "Mid Cap" },
  { symbol: "AFFLE", name: "Affle India Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "LAURUSLABS", name: "Laurus Labs Ltd", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "DEEPAKNTR", name: "Deepak Nitrite Ltd", sector: "Chemicals", cap: "Mid Cap" },
  { symbol: "IIFL", name: "IIFL Finance Ltd", sector: "Finance", cap: "Mid Cap" },
  { symbol: "HONAUT", name: "Honeywell Automation India", sector: "Engineering", cap: "Mid Cap" },
  { symbol: "MRF", name: "MRF Ltd", sector: "Auto Ancillary", cap: "Mid Cap" },
  { symbol: "GUJGASLTD", name: "Gujarat Gas Ltd", sector: "Oil & Gas", cap: "Mid Cap" },
  { symbol: "THERMAX", name: "Thermax Ltd", sector: "Engineering", cap: "Mid Cap" },
  { symbol: "SUPREMEIND", name: "Supreme Industries Ltd", sector: "Plastics", cap: "Mid Cap" },
  { symbol: "BATAINDIA", name: "Bata India Ltd", sector: "Footwear", cap: "Mid Cap" },
  { symbol: "WHIRLPOOL", name: "Whirlpool of India Ltd", sector: "Consumer Durables", cap: "Mid Cap" },
  { symbol: "KANSAINER", name: "Kansai Nerolac Paints Ltd", sector: "Paints", cap: "Mid Cap" },
  { symbol: "ABFRL", name: "Aditya Birla Fashion & Retail", sector: "Retail", cap: "Mid Cap" },
  { symbol: "APOLLOTYRE", name: "Apollo Tyres Ltd", sector: "Auto Ancillary", cap: "Mid Cap" },
  { symbol: "IPCALAB", name: "IPCA Laboratories Ltd", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "NATCOPHARM", name: "Natco Pharma Ltd", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "BLUEDART", name: "Blue Dart Express Ltd", sector: "Logistics", cap: "Mid Cap" },
  { symbol: "RELAXO", name: "Relaxo Footwears Ltd", sector: "Footwear", cap: "Mid Cap" },
  { symbol: "JUBILANT", name: "Jubilant Pharmova Ltd", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "LICHSGFIN", name: "LIC Housing Finance Ltd", sector: "Finance", cap: "Mid Cap" },
  { symbol: "INDIAMART", name: "IndiaMART InterMESH Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "KPITTECH", name: "KPIT Technologies Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "CYIENT", name: "Cyient Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "HAPPSTMNDS", name: "Happiest Minds Technologies", sector: "IT", cap: "Mid Cap" },
  { symbol: "ZENTEC", name: "Zensar Technologies Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "SONACOMS", name: "Sona BLW Precision Forgings", sector: "Auto Ancillary", cap: "Mid Cap" },
  { symbol: "VBL", name: "Varun Beverages Ltd", sector: "FMCG", cap: "Mid Cap" },
  { symbol: "TVSMOTOR", name: "TVS Motor Company Ltd", sector: "Auto", cap: "Mid Cap" },
  { symbol: "BHEL", name: "Bharat Heavy Electricals Ltd", sector: "Engineering", cap: "Mid Cap" },
  { symbol: "IRCTC", name: "Indian Railway Catering", sector: "Travel", cap: "Mid Cap" },
  { symbol: "EXIDEIND", name: "Exide Industries Ltd", sector: "Auto Ancillary", cap: "Mid Cap" },
  { symbol: "GODREJPROP", name: "Godrej Properties Ltd", sector: "Real Estate", cap: "Mid Cap" },
  { symbol: "EMAMILTD", name: "Emami Ltd", sector: "FMCG", cap: "Mid Cap" },
  { symbol: "SUNDRMFAST", name: "Sundram Fasteners Ltd", sector: "Auto Ancillary", cap: "Mid Cap" },
  { symbol: "RADICO", name: "Radico Khaitan Ltd", sector: "FMCG", cap: "Mid Cap" },
  { symbol: "FORTIS", name: "Fortis Healthcare Ltd", sector: "Healthcare", cap: "Mid Cap" },
  { symbol: "JSPL", name: "Jindal Saw Ltd", sector: "Metals", cap: "Mid Cap" },
  { symbol: "SONATSOFTW", name: "Sonata Software Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "MANAPPURAM", name: "Manappuram Finance Ltd", sector: "Finance", cap: "Mid Cap" },
  { symbol: "GMRINFRA", name: "GMR Infrastructure Ltd", sector: "Infrastructure", cap: "Mid Cap" },
  { symbol: "SKFINDIA", name: "SKF India Ltd", sector: "Engineering", cap: "Mid Cap" },
  { symbol: "BLUESTARCO", name: "Blue Star Ltd", sector: "Consumer Durables", cap: "Mid Cap" },
  { symbol: "TIMKEN", name: "Timken India Ltd", sector: "Engineering", cap: "Mid Cap" },
  { symbol: "CASTROLIND", name: "Castrol India Ltd", sector: "Oil & Gas", cap: "Mid Cap" },
  { symbol: "KAJARIACER", name: "Kajaria Ceramics Ltd", sector: "Building Materials", cap: "Mid Cap" },
  { symbol: "GRINDWELL", name: "Grindwell Norton Ltd", sector: "Engineering", cap: "Mid Cap" },
];

// Small cap stocks (Nifty Smallcap 250 + additional stocks)
export const SMALL_CAP_STOCKS: StockSeed[] = [
  { symbol: "ROUTE", name: "Route Mobile Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "TANLA", name: "Tanla Platforms Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "RBLBANK", name: "RBL Bank Ltd", sector: "Banking", cap: "Small Cap" },
  { symbol: "NATIONALUM", name: "National Aluminium Co", sector: "Metals", cap: "Small Cap" },
  { symbol: "HUDCO", name: "HUDCO Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "IRFC", name: "Indian Railway Finance Corp", sector: "Finance", cap: "Small Cap" },
  { symbol: "RVNL", name: "Rail Vikas Nigam Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "NHPC", name: "NHPC Ltd", sector: "Power", cap: "Small Cap" },
  { symbol: "IDEA", name: "Vodafone Idea Ltd", sector: "Telecom", cap: "Small Cap" },
  { symbol: "PAYTM", name: "One97 Communications Ltd", sector: "Fintech", cap: "Small Cap" },
  { symbol: "NYKAA", name: "FSN E-Commerce Ventures", sector: "Internet", cap: "Small Cap" },
  { symbol: "POLICYBZR", name: "PB Fintech Ltd", sector: "Fintech", cap: "Small Cap" },
  { symbol: "CARTRADE", name: "CarTrade Tech Ltd", sector: "Internet", cap: "Small Cap" },
  { symbol: "DELTACORP", name: "Delta Corp Ltd", sector: "Gaming", cap: "Small Cap" },
  { symbol: "WELCORP", name: "Welspun Corp Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "WOCKPHARMA", name: "Wockhardt Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "RAJESHEXPO", name: "Rajesh Exports Ltd", sector: "Gems & Jewellery", cap: "Small Cap" },
  { symbol: "AARTIIND", name: "Aarti Industries Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "TATACHEM", name: "Tata Chemicals Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "MAHINDCIE", name: "Mahindra CIE Automotive", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "APLAPOLLO", name: "APL Apollo Tubes Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "BIRLACORPN", name: "Birla Corporation Ltd", sector: "Cement", cap: "Small Cap" },
  { symbol: "CENTURYTEX", name: "Century Textiles & Industries", sector: "Textiles", cap: "Small Cap" },
  { symbol: "DCMSHRIRAM", name: "DCM Shriram Ltd", sector: "Diversified", cap: "Small Cap" },
  { symbol: "CENTURYPLY", name: "Century Plyboards India", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "CANFINHOME", name: "Can Fin Homes Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "FINCABLES", name: "Finolex Cables Ltd", sector: "Cables", cap: "Small Cap" },
  { symbol: "FINPIPE", name: "Finolex Industries Ltd", sector: "Plastics", cap: "Small Cap" },
  { symbol: "TVSSCS", name: "TVS Supply Chain Solutions", sector: "Logistics", cap: "Small Cap" },
  { symbol: "TRITURBINE", name: "Triveni Turbine Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "JKCEMENT", name: "JK Cement Ltd", sector: "Cement", cap: "Small Cap" },
  { symbol: "JKLAKSHMI", name: "JK Lakshmi Cement Ltd", sector: "Cement", cap: "Small Cap" },
  { symbol: "VGUARD", name: "V-Guard Industries Ltd", sector: "Consumer Durables", cap: "Small Cap" },
  { symbol: "BALAMINES", name: "Balaji Amines Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "GLENMARK", name: "Glenmark Pharmaceuticals", sector: "Pharma", cap: "Small Cap" },
  { symbol: "IDFC", name: "IDFC Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "IFCI", name: "IFCI Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "IBREALEST", name: "Indiabulls Real Estate", sector: "Real Estate", cap: "Small Cap" },
  { symbol: "RAJRATAN", name: "Rajratan Global Wire Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "SOBHA", name: "Sobha Ltd", sector: "Real Estate", cap: "Small Cap" },
  { symbol: "SUNTV", name: "Sun TV Network Ltd", sector: "Media", cap: "Small Cap" },
  { symbol: "TV18BRDCST", name: "TV18 Broadcast Ltd", sector: "Media", cap: "Small Cap" },
  { symbol: "PVRINOX", name: "PVR INOX Ltd", sector: "Media", cap: "Small Cap" },
  { symbol: "NCC", name: "NCC Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "TEJASNET", name: "Tejas Networks Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "MMTC", name: "MMTC Ltd", sector: "Trading", cap: "Small Cap" },
  { symbol: "MOIL", name: "MOIL Ltd", sector: "Mining", cap: "Small Cap" },
  { symbol: "HFCL", name: "HFCL Ltd", sector: "Telecom", cap: "Small Cap" },
  { symbol: "HEIDELBERG", name: "Heidelberg Cement India", sector: "Cement", cap: "Small Cap" },
  { symbol: "JSWENERGY", name: "JSW Energy Ltd", sector: "Power", cap: "Small Cap" },
  { symbol: "JYOTHYLAB", name: "Jyothy Labs Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "KALPATPOWR", name: "Kalpataru Projects Intl", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "KEI", name: "KEI Industries Ltd", sector: "Cables", cap: "Small Cap" },
  { symbol: "KRBL", name: "KRBL Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "LXCHEM", name: "Laxmi Organic Industries", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "MAZDOCK", name: "Mazagon Dock Shipbuilders", sector: "Shipbuilding", cap: "Small Cap" },
  { symbol: "NAVINFLUOR", name: "Navin Fluorine Intl", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "ORIENTELEC", name: "Orient Electric Ltd", sector: "Consumer Durables", cap: "Small Cap" },
  { symbol: "ORIENTCEM", name: "Orient Cement Ltd", sector: "Cement", cap: "Small Cap" },
  { symbol: "PGHL", name: "Procter & Gamble Health", sector: "Pharma", cap: "Small Cap" },
  { symbol: "PRAJIND", name: "Praj Industries Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "PRSMJOHNSN", name: "Prism Johnson Ltd", sector: "Cement", cap: "Small Cap" },
  { symbol: "PTC", name: "PTC India Ltd", sector: "Power", cap: "Small Cap" },
  { symbol: "QUESS", name: "Quess Corp Ltd", sector: "Staffing", cap: "Small Cap" },
  { symbol: "RAIN", name: "Rain Industries Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "RALLIS", name: "Rallis India Ltd", sector: "Agro Chemicals", cap: "Small Cap" },
  { symbol: "RCF", name: "Rashtriya Chemicals & Fertilizers", sector: "Fertilizers", cap: "Small Cap" },
  { symbol: "REDINGTON", name: "Redington India Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "SCI", name: "Shipping Corporation of India", sector: "Logistics", cap: "Small Cap" },
  { symbol: "SJVN", name: "SJVN Ltd", sector: "Power", cap: "Small Cap" },
  { symbol: "STAR", name: "Strides Pharma Science", sector: "Pharma", cap: "Small Cap" },
  { symbol: "STARCEMENT", name: "Star Cement Ltd", sector: "Cement", cap: "Small Cap" },
  { symbol: "SRF", name: "SRF Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "SUPRAJIT", name: "Suprajit Engineering Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "SWANENERGY", name: "Swan Energy Ltd", sector: "Diversified", cap: "Small Cap" },
  { symbol: "SYMPHONY", name: "Symphony Ltd", sector: "Consumer Durables", cap: "Small Cap" },
  { symbol: "TATACOMM", name: "Tata Communications Ltd", sector: "Telecom", cap: "Small Cap" },
  { symbol: "TATACOFFEE", name: "Tata Coffee Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "TATAINVEST", name: "Tata Investment Corporation", sector: "Finance", cap: "Small Cap" },
  { symbol: "TATAMETALI", name: "Tata Metaliks Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "TCNSBRANDS", name: "TCNS Clothing Co Ltd", sector: "Retail", cap: "Small Cap" },
  { symbol: "TEAMLEASE", name: "TeamLease Services Ltd", sector: "Staffing", cap: "Small Cap" },
  { symbol: "THERMAX", name: "Thermax Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "TIMESGTY", name: "Times Guaranty Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "TORNTPOWER", name: "Torrent Power Ltd", sector: "Power", cap: "Small Cap" },
  { symbol: "TRIDENT", name: "Trident Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "UFLEX", name: "Uflex Ltd", sector: "Packaging", cap: "Small Cap" },
  { symbol: "UJJIVAN", name: "Ujjivan Financial Services", sector: "Finance", cap: "Small Cap" },
  { symbol: "UJJIVANSFB", name: "Ujjivan Small Finance Bank", sector: "Banking", cap: "Small Cap" },
  { symbol: "UCOBANK", name: "UCO Bank", sector: "Banking", cap: "Small Cap" },
  { symbol: "VTL", name: "Vardhman Textiles Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "WABAG", name: "VA Tech Wabag Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "WELSPUNIND", name: "Welspun India Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "WESTLIFE", name: "Westlife Foodworld Ltd", sector: "QSR", cap: "Small Cap" },
  { symbol: "YESBANK", name: "Yes Bank Ltd", sector: "Banking", cap: "Small Cap" },
  { symbol: "ZENSARTECH", name: "Zensar Technologies Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "ZEELEARN", name: "Zee Learn Ltd", sector: "Education", cap: "Small Cap" },
  { symbol: "ECLERX", name: "eClerx Services Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "HEG", name: "HEG Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "GRAPHITE", name: "Graphite India Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "GULFOILLUB", name: "Gulf Oil Lubricants India", sector: "Oil & Gas", cap: "Small Cap" },
  { symbol: "GPPL", name: "Gujarat Pipavav Port Ltd", sector: "Logistics", cap: "Small Cap" },
  { symbol: "GRSE", name: "Garden Reach Shipbuilders", sector: "Shipbuilding", cap: "Small Cap" },
  { symbol: "GSFC", name: "Gujarat State Fertilizers", sector: "Fertilizers", cap: "Small Cap" },
  { symbol: "GSPL", name: "Gujarat State Petronet Ltd", sector: "Oil & Gas", cap: "Small Cap" },
  { symbol: "GNFC", name: "Gujarat Narmada Valley Fertilizers", sector: "Fertilizers", cap: "Small Cap" },
  { symbol: "EIDPARRY", name: "EID Parry India Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "ELGIEQUIP", name: "Elgi Equipments Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "ELECON", name: "Elecon Engineering Company", sector: "Engineering", cap: "Small Cap" },
  { symbol: "ENDURANCE", name: "Endurance Technologies Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "EQUITAS", name: "Equitas Holdings Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "EQUITASBNK", name: "Equitas Small Finance Bank", sector: "Banking", cap: "Small Cap" },
  { symbol: "ESABINDIA", name: "ESAB India Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "EVEREADY", name: "Eveready Industries India", sector: "Consumer Durables", cap: "Small Cap" },
  { symbol: "FLFL", name: "Future Lifestyle Fashions", sector: "Retail", cap: "Small Cap" },
  { symbol: "FRETAIL", name: "Future Retail Ltd", sector: "Retail", cap: "Small Cap" },
  { symbol: "FSC", name: "Future Supply Chain Solutions", sector: "Logistics", cap: "Small Cap" },
  { symbol: "GABRIEL", name: "Gabriel India Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "GALAXYSURF", name: "Galaxy Surfactants Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "GARFIBRES", name: "Garware Technical Fibres", sector: "Textiles", cap: "Small Cap" },
  { symbol: "GATEWAY", name: "Gateway Distriparks Ltd", sector: "Logistics", cap: "Small Cap" },
  { symbol: "GDL", name: "Gateway Distriparks Ltd", sector: "Logistics", cap: "Small Cap" },
  { symbol: "GEPIL", name: "GE Power India Ltd", sector: "Power", cap: "Small Cap" },
  { symbol: "GET&D", name: "GE T&D India Ltd", sector: "Power", cap: "Small Cap" },
  { symbol: "GHCL", name: "GHCL Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "GILLETTE", name: "Gillette India Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "GLAXO", name: "GlaxoSmithKline Pharmaceuticals", sector: "Pharma", cap: "Small Cap" },
  { symbol: "GMDCLTD", name: "Gujarat Mineral Development", sector: "Mining", cap: "Small Cap" },
  { symbol: "GODREJAGRO", name: "Godrej Agrovet Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "GODREJIND", name: "Godrej Industries Ltd", sector: "Diversified", cap: "Small Cap" },
  { symbol: "GRANULES", name: "Granules India Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "GREENPLY", name: "Greenply Industries Ltd", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "GRINDWELL", name: "Grindwell Norton Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "CERA", name: "Cera Sanitaryware Ltd", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "KPRMILL", name: "KPR Mill Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "KSB", name: "KSB Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "LEMONTREE", name: "Lemon Tree Hotels Ltd", sector: "Hotels", cap: "Small Cap" },
  { symbol: "LINDEINDIA", name: "Linde India Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "LUXIND", name: "Lux Industries Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "MAITHANALL", name: "Maithan Alloys Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "MAPMYINDIA", name: "CE Info Systems Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "MARKSANS", name: "Marksans Pharma Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "MASTEK", name: "Mastek Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "MAYURUNIQ", name: "Mayur Uniquoters Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "MCX", name: "Multi Commodity Exchange", sector: "Finance", cap: "Small Cap" },
  { symbol: "MINDACORP", name: "Minda Corporation Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "MINDAIND", name: "Minda Industries Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "MGL", name: "Mahanagar Gas Ltd", sector: "Oil & Gas", cap: "Small Cap" },
  { symbol: "MIDHANI", name: "Mishra Dhatu Nigam Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "MINDTREE", name: "MindTree Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "MOREPENLAB", name: "Morepen Laboratories Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "MOTILALOFS", name: "Motilal Oswal Financial Services", sector: "Finance", cap: "Small Cap" },
  { symbol: "MRPL", name: "Mangalore Refinery & Petrochemicals", sector: "Oil & Gas", cap: "Small Cap" },
  { symbol: "MRF", name: "MRF Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "MSTCLTD", name: "MSTC Ltd", sector: "Trading", cap: "Small Cap" },
  { symbol: "NAM-INDIA", name: "Nippon Life India Asset Management", sector: "Finance", cap: "Small Cap" },
  { symbol: "NBCC", name: "NBCC India Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "NFL", name: "National Fertilizers Ltd", sector: "Fertilizers", cap: "Small Cap" },
  { symbol: "NH", name: "Narayana Hrudayalaya Ltd", sector: "Healthcare", cap: "Small Cap" },
  { symbol: "NILKAMAL", name: "Nilkamal Ltd", sector: "Plastics", cap: "Small Cap" },
  { symbol: "NLCINDIA", name: "NLC India Ltd", sector: "Power", cap: "Small Cap" },
  { symbol: "NOCIL", name: "NOCIL Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "OFSS", name: "Oracle Financial Services", sector: "IT", cap: "Small Cap" },
  { symbol: "OIL", name: "Oil India Ltd", sector: "Oil & Gas", cap: "Small Cap" },
  { symbol: "OLECTRA", name: "Olectra Greentech Ltd", sector: "Auto", cap: "Small Cap" },
  { symbol: "OMAXE", name: "Omaxe Ltd", sector: "Real Estate", cap: "Small Cap" },
  { symbol: "PANAMAPET", name: "Panama Petrochem Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "PNCINFRA", name: "PNC Infratech Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "POWERINDIA", name: "Hitachi Energy India Ltd", sector: "Power", cap: "Small Cap" },
  { symbol: "PRINCEPIPE", name: "Prince Pipes And Fittings", sector: "Plastics", cap: "Small Cap" },
  { symbol: "PSB", name: "Punjab & Sind Bank", sector: "Banking", cap: "Small Cap" },
  { symbol: "QUICKHEAL", name: "Quick Heal Technologies", sector: "IT", cap: "Small Cap" },
  { symbol: "RAMCOCEM", name: "Ramco Cements Ltd", sector: "Cement", cap: "Small Cap" },
  { symbol: "RATEGAIN", name: "RateGain Travel Technologies", sector: "IT", cap: "Small Cap" },
  { symbol: "RAYMOND", name: "Raymond Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "RELIGARE", name: "Religare Enterprises Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "RESPONSIIND", name: "Responsive Industries Ltd", sector: "Plastics", cap: "Small Cap" },
  { symbol: "RITES", name: "RITES Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "RVNL", name: "Rail Vikas Nigam Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "SADBHAV", name: "Sadbhav Engineering Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "SANOFI", name: "Sanofi India Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "SARDAEN", name: "Sarda Energy & Minerals", sector: "Power", cap: "Small Cap" },
  { symbol: "SASKEN", name: "Sasken Technologies Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "SCHAEFFLER", name: "Schaeffler India Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "SCHNEIDER", name: "Schneider Electric Infrastructure", sector: "Power", cap: "Small Cap" },
  { symbol: "SHANKARA", name: "Shankara Building Products", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "SHARDACROP", name: "Sharda Cropchem Ltd", sector: "Agro Chemicals", cap: "Small Cap" },
  { symbol: "SHILPAMED", name: "Shilpa Medicare Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "SIS", name: "SIS Ltd", sector: "Security", cap: "Small Cap" },
  { symbol: "SKFINDIA", name: "SKF India Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "SNOWMAN", name: "Snowman Logistics Ltd", sector: "Logistics", cap: "Small Cap" },
  { symbol: "SOLARA", name: "Solara Active Pharma Sciences", sector: "Pharma", cap: "Small Cap" },
  { symbol: "SOLARINDS", name: "Solar Industries India", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "SOMANYCERA", name: "Somany Ceramics Ltd", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "SPARC", name: "Sun Pharma Advanced Research", sector: "Pharma", cap: "Small Cap" },
  { symbol: "SPANDANA", name: "Spandana Sphoorty Financial", sector: "Finance", cap: "Small Cap" },
  { symbol: "SPICEJET", name: "SpiceJet Ltd", sector: "Aviation", cap: "Small Cap" },
  { symbol: "SSWL", name: "Steel Strips Wheels Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "STLTECH", name: "Sterlite Technologies Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "SUBROS", name: "Subros Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "SUDARSCHEM", name: "Sudarshan Chemical Industries", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "SUMICHEM", name: "Sumitomo Chemical India", sector: "Agro Chemicals", cap: "Small Cap" },
  { symbol: "SUNCLAYLTD", name: "Sundaram Clayton Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "SUVEN", name: "Suven Pharmaceuticals Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "SWARAJENG", name: "Swaraj Engines Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "TAKE", name: "Take Solutions Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "TANLATECH", name: "Tanla Platforms Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "TASTYBITE", name: "Tasty Bite Eatables Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "TBZ", name: "Tribhovandas Bhimji Zaveri", sector: "Gems & Jewellery", cap: "Small Cap" },
  { symbol: "TCI", name: "Transport Corporation of India", sector: "Logistics", cap: "Small Cap" },
  { symbol: "TCNSBRANDS", name: "TCNS Clothing Co Ltd", sector: "Retail", cap: "Small Cap" },
  { symbol: "TDPOWERSYS", name: "TD Power Systems Ltd", sector: "Power", cap: "Small Cap" },
  { symbol: "TECHNOE", name: "Techno Electric & Engineering", sector: "Power", cap: "Small Cap" },
  { symbol: "TEXRAIL", name: "Texmaco Rail & Engineering", sector: "Engineering", cap: "Small Cap" },
  { symbol: "THERMAX", name: "Thermax Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "THOMASCOOK", name: "Thomas Cook India Ltd", sector: "Travel", cap: "Small Cap" },
  { symbol: "THYROCARE", name: "Thyrocare Technologies Ltd", sector: "Healthcare", cap: "Small Cap" },
  { symbol: "TIIL", name: "Technocraft Industries India", sector: "Engineering", cap: "Small Cap" },
  { symbol: "TINPLATE", name: "Tinplate Company of India", sector: "Metals", cap: "Small Cap" },
  { symbol: "TITAN", name: "Titan Company Ltd", sector: "Consumer Goods", cap: "Small Cap" },
  { symbol: "TNPL", name: "Tamil Nadu Newsprint & Papers", sector: "Paper", cap: "Small Cap" },
  { symbol: "TTKPRESTIG", name: "TTK Prestige Ltd", sector: "Consumer Durables", cap: "Small Cap" },
  { symbol: "TVTODAY", name: "TV Today Network Ltd", sector: "Media", cap: "Small Cap" },
  { symbol: "TWL", name: "Titagarh Rail Systems Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "UFLEX", name: "Uflex Ltd", sector: "Packaging", cap: "Small Cap" },
  { symbol: "UFO", name: "UFO Moviez India Ltd", sector: "Media", cap: "Small Cap" },
  { symbol: "UNICHEMLAB", name: "Unichem Laboratories Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "UNIONBANK", name: "Union Bank of India", sector: "Banking", cap: "Small Cap" },
  { symbol: "UPL", name: "UPL Ltd", sector: "Agro Chemicals", cap: "Small Cap" },
  { symbol: "UTIAMC", name: "UTI Asset Management Company", sector: "Finance", cap: "Small Cap" },
  { symbol: "VAIBHAVGBL", name: "Vaibhav Global Ltd", sector: "Gems & Jewellery", cap: "Small Cap" },
  { symbol: "VAKRANGEE", name: "Vakrangee Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "VALUEIND", name: "Value Industries Ltd", sector: "Consumer Durables", cap: "Small Cap" },
  { symbol: "VBL", name: "Varun Beverages Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "VEDL", name: "Vedanta Ltd", sector: "Mining", cap: "Small Cap" },
  { symbol: "VENKEYS", name: "Venky's India Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "VESUVIUS", name: "Vesuvius India Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "VGUARD", name: "V-Guard Industries Ltd", sector: "Consumer Durables", cap: "Small Cap" },
  { symbol: "VINATIORGA", name: "Vinati Organics Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "VIPIND", name: "VIP Industries Ltd", sector: "Consumer Durables", cap: "Small Cap" },
  { symbol: "VMART", name: "V-Mart Retail Ltd", sector: "Retail", cap: "Small Cap" },
  { symbol: "VOLTAMP", name: "Voltamp Transformers Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "VOLTAS", name: "Voltas Ltd", sector: "Consumer Durables", cap: "Small Cap" },
  { symbol: "VRL", name: "VRL Logistics Ltd", sector: "Logistics", cap: "Small Cap" },
  { symbol: "VSTIND", name: "VST Industries Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "WABCOINDIA", name: "WABCO India Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "WELENT", name: "Welspun Enterprises Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "WHIRLPOOL", name: "Whirlpool of India Ltd", sector: "Consumer Durables", cap: "Small Cap" },
  { symbol: "WINDMACHIN", name: "Windsor Machines Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "WONDERLA", name: "Wonderla Holidays Ltd", sector: "Entertainment", cap: "Small Cap" },
  { symbol: "WSTCSTPAPR", name: "West Coast Paper Mills", sector: "Paper", cap: "Small Cap" },
  { symbol: "XPROINDIA", name: "Xpro India Ltd", sector: "Plastics", cap: "Small Cap" },
  { symbol: "YESBANK", name: "Yes Bank Ltd", sector: "Banking", cap: "Small Cap" },
  { symbol: "ZEEL", name: "Zee Entertainment Enterprises", sector: "Media", cap: "Small Cap" },
  { symbol: "ZENITHSTL", name: "Zenith Steel Pipes & Industries", sector: "Metals", cap: "Small Cap" },
  { symbol: "ZENSARTECH", name: "Zensar Technologies Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "ZODIACJRD", name: "Zodiac JRD-MKJ Ltd", sector: "Retail", cap: "Small Cap" },
  { symbol: "ZUARI", name: "Zuari Agro Chemicals Ltd", sector: "Fertilizers", cap: "Small Cap" },
  { symbol: "ZUARIGLOB", name: "Zuari Global Ltd", sector: "Diversified", cap: "Small Cap" },
];

// Additional BSE stocks
export const ADDITIONAL_BSE_STOCKS: StockSeed[] = [
  { symbol: "3MINDIA", name: "3M India Ltd", sector: "Diversified", cap: "Mid Cap" },
  { symbol: "AADHARHFC", name: "Aadhar Housing Finance Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "AARTIDRUGS", name: "Aarti Drugs Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "AARTISURF", name: "Aarti Surfactants Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "AARVEEDEN", name: "Aarvee Denims & Exports", sector: "Textiles", cap: "Small Cap" },
  { symbol: "AATMAJ", name: "Aatmaj Healthcare Ltd", sector: "Healthcare", cap: "Small Cap" },
  { symbol: "ABCAPITAL", name: "Aditya Birla Capital Ltd", sector: "Finance", cap: "Mid Cap" },
  { symbol: "ABMINTL", name: "ABM International Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "ABSLAMC", name: "Aditya Birla Sun Life AMC", sector: "Finance", cap: "Mid Cap" },
  { symbol: "ACCELYA", name: "Accelya Solutions India", sector: "IT", cap: "Small Cap" },
  { symbol: "ACE", name: "Action Construction Equipment", sector: "Engineering", cap: "Small Cap" },
  { symbol: "ADANIGREEN", name: "Adani Green Energy Ltd", sector: "Power", cap: "Large Cap" },
  { symbol: "ADANIPOWER", name: "Adani Power Ltd", sector: "Power", cap: "Large Cap" },
  { symbol: "ADANITRANS", name: "Adani Transmission Ltd", sector: "Power", cap: "Large Cap" },
  { symbol: "ADFFOODS", name: "ADF Foods Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "ADORWELD", name: "Ador Welding Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "ADVENZYMES", name: "Advanced Enzyme Technologies", sector: "Pharma", cap: "Small Cap" },
  { symbol: "AEGISCHEM", name: "Aegis Logistics Ltd", sector: "Logistics", cap: "Mid Cap" },
  { symbol: "AFFLE", name: "Affle India Ltd", sector: "IT", cap: "Mid Cap" },
  { symbol: "AGARIND", name: "Agarwal Industrial Corporation", sector: "Metals", cap: "Small Cap" },
  { symbol: "AGRITECH", name: "Agri-Tech India Ltd", sector: "Agro", cap: "Small Cap" },
  { symbol: "AHLUCONT", name: "Ahluwalia Contracts India", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "AIAENG", name: "AIA Engineering Ltd", sector: "Engineering", cap: "Mid Cap" },
  { symbol: "AIRAN", name: "Airan Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "AJANTPHARM", name: "Ajanta Pharma Ltd", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "AJMERA", name: "Ajmera Realty & Infra India", sector: "Real Estate", cap: "Small Cap" },
  { symbol: "AKSHOPTFBR", name: "Aksh Optifibre Ltd", sector: "Cables", cap: "Small Cap" },
  { symbol: "AKZOINDIA", name: "Akzo Nobel India Ltd", sector: "Paints", cap: "Mid Cap" },
  { symbol: "ALANKIT", name: "Alankit Ltd", sector: "Finance", cap: "Small Cap" },
  { symbol: "ALBERTDAVD", name: "Albert David Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "ALEMBICLTD", name: "Alembic Ltd", sector: "Pharma", cap: "Small Cap" },
  { symbol: "ALICON", name: "Alicon Castalloy Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "ALKALI", name: "Alkali Metals Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "ALLCARGO", name: "Allcargo Logistics Ltd", sector: "Logistics", cap: "Mid Cap" },
  { symbol: "ALLSEC", name: "Allsec Technologies Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "ALMONDZ", name: "Almondz Global Securities", sector: "Finance", cap: "Small Cap" },
  { symbol: "ALOKTEXT", name: "Alok Industries Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "ALPHAGEO", name: "Alphageo India Ltd", sector: "Oil & Gas", cap: "Small Cap" },
  { symbol: "AMARAJABAT", name: "Amara Raja Energy & Mobility", sector: "Auto Ancillary", cap: "Mid Cap" },
  { symbol: "AMBER", name: "Amber Enterprises India", sector: "Consumer Durables", cap: "Mid Cap" },
  { symbol: "AMBIKCO", name: "Ambika Cotton Mills Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "AMBUJACEM", name: "Ambuja Cements Ltd", sector: "Cement", cap: "Large Cap" },
  { symbol: "AMDIND", name: "AMD Industries Ltd", sector: "Packaging", cap: "Small Cap" },
  { symbol: "AMJLAND", name: "Amj Land Holdings Ltd", sector: "Real Estate", cap: "Small Cap" },
  { symbol: "ANANTRAJ", name: "Anant Raj Ltd", sector: "Real Estate", cap: "Small Cap" },
  { symbol: "ANDHRSUGAR", name: "Andhra Sugars Ltd", sector: "Sugar", cap: "Small Cap" },
  { symbol: "ANGELONE", name: "Angel One Ltd", sector: "Finance", cap: "Mid Cap" },
  { symbol: "ANIKINDS", name: "Anik Industries Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "ANKITMETAL", name: "Ankit Metal & Power Ltd", sector: "Metals", cap: "Small Cap" },
  { symbol: "ANTGRAPHIC", name: "Ant Graphics Pvt Ltd", sector: "Media", cap: "Small Cap" },
  { symbol: "ANUP", name: "Anup Engineering Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "APARINDS", name: "Apar Industries Ltd", sector: "Cables", cap: "Mid Cap" },
  { symbol: "APCOTEXIND", name: "Apcotex Industries Ltd", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "APEX", name: "Apex Frozen Foods Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "APLAPOLLO", name: "APL Apollo Tubes Ltd", sector: "Metals", cap: "Mid Cap" },
  { symbol: "APLLTD", name: "Alembic Pharmaceuticals Ltd", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "APOLLO", name: "Apollo Micro Systems Ltd", sector: "Defence", cap: "Small Cap" },
  { symbol: "APOLLOPIPE", name: "Apollo Pipes Ltd", sector: "Plastics", cap: "Small Cap" },
  { symbol: "APTECHT", name: "Aptech Ltd", sector: "Education", cap: "Small Cap" },
  { symbol: "APTUS", name: "Aptus Value Housing Finance", sector: "Finance", cap: "Mid Cap" },
  { symbol: "ARCHIDPLY", name: "Archidply Industries Ltd", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "ARCHIES", name: "Archies Ltd", sector: "Retail", cap: "Small Cap" },
  { symbol: "ARCOTECH", name: "Arcotech Ltd", sector: "Engineering", cap: "Small Cap" },
  { symbol: "ARE&M", name: "Amara Raja Energy & Mobility", sector: "Auto Ancillary", cap: "Mid Cap" },
  { symbol: "ARIHANTCAP", name: "Arihant Capital Markets", sector: "Finance", cap: "Small Cap" },
  { symbol: "ARIHANTSUP", name: "Arihant Superstructures", sector: "Real Estate", cap: "Small Cap" },
  { symbol: "ARMANFIN", name: "Arman Financial Services", sector: "Finance", cap: "Small Cap" },
  { symbol: "AROCHEM", name: "Aroma Enterprises India", sector: "Chemicals", cap: "Small Cap" },
  { symbol: "ARROWGREEN", name: "Arrow Greentech Ltd", sector: "Diversified", cap: "Small Cap" },
  { symbol: "ARSHIYA", name: "Arshiya Ltd", sector: "Logistics", cap: "Small Cap" },
  { symbol: "ARTEMISMED", name: "Artemis Medicare Services", sector: "Healthcare", cap: "Small Cap" },
  { symbol: "ARVSMART", name: "Arvind Smartspaces Ltd", sector: "Real Estate", cap: "Small Cap" },
  { symbol: "ARVIND", name: "Arvind Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "ARVINDFASN", name: "Arvind Fashions Ltd", sector: "Retail", cap: "Small Cap" },
  { symbol: "ASAHIINDIA", name: "Asahi India Glass Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "ASHIANA", name: "Ashiana Housing Ltd", sector: "Real Estate", cap: "Small Cap" },
  { symbol: "ASHIMASYN", name: "Ashima Ltd", sector: "Textiles", cap: "Small Cap" },
  { symbol: "ASHOKA", name: "Ashoka Buildcon Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "ASIANHOTNR", name: "Asian Hotels North Ltd", sector: "Hotels", cap: "Small Cap" },
  { symbol: "ASIANTILES", name: "Asian Granito India Ltd", sector: "Building Materials", cap: "Small Cap" },
  { symbol: "ASTEC", name: "Astec LifeSciences Ltd", sector: "Agro Chemicals", cap: "Small Cap" },
  { symbol: "ASTRAMICRO", name: "Astra Microwave Products", sector: "Defence", cap: "Small Cap" },
  { symbol: "ASTRAZEN", name: "AstraZeneca Pharma India", sector: "Pharma", cap: "Small Cap" },
  { symbol: "ASTRAL", name: "Astral Ltd", sector: "Plastics", cap: "Mid Cap" },
  { symbol: "ATALREAL", name: "Atal Realtech Ltd", sector: "Real Estate", cap: "Small Cap" },
  { symbol: "ATFL", name: "Agro Tech Foods Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "ATLANTAA", name: "Atlantaa Ltd", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "ATLASBIKE", name: "Atlas Cycles Haryana Ltd", sector: "Auto", cap: "Small Cap" },
  { symbol: "ATULAUTO", name: "Atul Auto Ltd", sector: "Auto", cap: "Small Cap" },
  { symbol: "AUBANK", name: "AU Small Finance Bank", sector: "Banking", cap: "Mid Cap" },
  { symbol: "AURIONPRO", name: "Aurionpro Solutions Ltd", sector: "IT", cap: "Small Cap" },
  { symbol: "AUROPHARM", name: "Aurobindo Pharma Ltd", sector: "Pharma", cap: "Mid Cap" },
  { symbol: "AUTOAXLES", name: "Automotive Axles Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "AUTOIND", name: "Autoline Industries Ltd", sector: "Auto Ancillary", cap: "Small Cap" },
  { symbol: "AVADHSUGAR", name: "Avadh Sugar & Energy Ltd", sector: "Sugar", cap: "Small Cap" },
  { symbol: "AVANTIFEED", name: "Avanti Feeds Ltd", sector: "FMCG", cap: "Small Cap" },
  { symbol: "AWHCL", name: "Antony Waste Handling Cell", sector: "Infrastructure", cap: "Small Cap" },
  { symbol: "AXISBANK", name: "Axis Bank Ltd", sector: "Banking", cap: "Large Cap" },
  { symbol: "AXISCADES", name: "AXISCADES Technologies", sector: "IT", cap: "Small Cap" },
];

// Combine all stocks
export const ALL_STOCKS: StockSeed[] = [
  ...LARGE_CAP_STOCKS,
  ...MID_CAP_STOCKS,
  ...SMALL_CAP_STOCKS,
  ...ADDITIONAL_BSE_STOCKS,
];

export default ALL_STOCKS;
